### ISSUE TITLE
Web Chat doesn't work

### ISSUE THREAD

**Issue by maxwellsarmento** [MicrosoftDocs/bot-docs#1000]
Message Bot source published. Preparing bot application to run the new source.
Deployment successful!, after that, I've deleted the bot secret and saved it. Still, when trying to use web chat, got a blank screen, and when said "hi" the message couldn't be sent. How do I confirm if the bot is ok? Or whatelse did I miss? It is working in the emulator. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by maxwellsarmento** [comment]
Now it just show "Waiting for bot to be ready after deployment"

**Comment by Kaiqb** [comment]
This typically happens when the deployment was not successful, even though you don't get any messages. 

If your bot works locally in the Emulator, then refer to this document on [deployment](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp). 

Note that we used to create a .bot file when you created a bot in Azure, but now we don't. You should use appsettings.json or .env file.
