### ISSUE TITLE
Get inputs from the Adaptive card

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1053]
I have a simple adpative card with a textbox and a submit action button. How to received the input from the card ? Please NOTE I am trying to this inside a Dialog class.

Also in V3 we use to write "context.Wait(this.MessageReceivedAsync);" to wait for the user to provide the input in the card and then receive the message in  MessageReceivedAsync as shown below:

private async Task ShowInputCard(IDialogContext context)
        {
            var card = // get card content

            var message = context.MakeMessage();
            message.Attachments.Add(card);
            await context.PostAsync(message);
            context.Wait(this.MessageReceivedAsync);
        }

async Task MessageReceivedAsync(IDialogContext context, IAwaitable&lt;object&gt; result)
{
     // get the user input from result 
      var activity = await result as IMessageActivity;
}

In v4 I am struggling to get this working. Please assist (With a code sample would be great)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607856cb-baae-c401-5b34-876b5018771d
* Version Independent ID: 77df1de7-7b2e-a546-1280-a66121039a94
* Content: [Add media to messages - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-media-attachments.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-media-attachments.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by vikramdadwal** [comment]
Please assist

**Comment by EricDahlvang** [comment]
The result will be in the activity.Value property.

**Comment by DanDev33** [comment]
Per your request, we put together a small sample showing one of the ways you can access this information within a dialog. This example extends the current C# sample 06.using-cards by adding a validator. We first added text input and button functionality to the existing adaptive card by adding the following code just before the final bracket of adaptiveCard.json, found in the resources folder:

,
  "actions": [
    {
      "type": "Action.ShowCard",
      "title": "Text",
      "card": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "Input.Text",
            "id": "text",
            "isMultiline": true,
            "placeholder": "Enter your comment"
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "OK"
          }
        ]
      }
    }
  ]

Note that the input field is labeled "text" so [text.<textbox input>] is what we'll need to look for in the sample validator.  The validator code will be added into: MainDialog.cs in the dialogs folder.
Because an Adaptive Card attaches comment text data as Value.[text.<textbox input>] our validator uses Newtonsoft.json to first convert this to a JObject, and then create a trimmed text string for comparison. So add:
     using Newtonsoft.Json.Linq;
to MainDialog.cs and install the latest stable nuget package of Newtonsoft.Json.

Below is the validator code. I've added the logic flow into the code comments. We placed this just after the closed brace public for  declaration of MainDialog:

 private async Task<bool> ChoiceValidator(
       PromptValidatorContext<FoundChoice> promptContext,
       CancellationToken cancellationToken)
{
     // Retrieves Adaptive Card comment text as JObject.
     // looks for JObject field "text" and converts that input into a trimmed text string.
      var jobject = promptContext.Context.Activity.Value as JObject;
      var jtoken = jobject?["text"];
      var text = jtoken?.Value<string>().Trim();

      // Logic: 1. if succeeded = true, just return promptContext
      //            2. if false, see if JObject contained Adaptive Card input.
      //               No = (bad input) return promptContext
      //               Yes = update Value field with JBoject text string, return "true".
      if (!promptContext.Recognized.Succeeded && text != null)
      {
           var choice = promptContext.Options.Choices.FirstOrDefault(
           c => c.Value.Equals(text, StringComparison.InvariantCultureIgnoreCase));
           if (choice != null)
           {
               promptContext.Recognized.Value = new FoundChoice
                {
                   Value = choice.Value,
                 };
                return true;
           }
      }
     return promptContext.Recognized.Succeeded;
}

Now above in the MainDialog declaration change:

// Define the main dialog and its related components.
AddDialog(new ChoicePrompt(nameof(ChoicePrompt)));

to:

// Define the main dialog and its related components.
AddDialog(new ChoicePrompt(nameof(ChoicePrompt), ChoiceValidator));

This will invoke your validator to look for Adaptive Card input each time a new ChoicePrompt is created.

NOTES - This is just one way to look for Adaptive Card input from a textbox and submit action button.
            - The validator looks for the case sensitive label you provided for your textbox in the card .json.
            - The input text must match one of the valid text choices, in this sample found in GetChoices().

Hope this sample helps show you one way to use Adaptive Card inputs within a v4 bot dialog class.

**Comment by HowdySys** [comment]
Is this sample still out there? I'm not finding where this was placed - looked in sample 6 & 7. I apologize if I'm simply overlooking it!
