### ISSUE TITLE
Web Chat not working: 404 NotFound issues

### ISSUE THREAD

**Issue by andreschort** [MicrosoftDocs/bot-docs#1124]
After a successful deployment the Web Chat says "not sent" below every message. The Web Chat channel shows issues with message: "There was an error sending this message to your bot: HTTP status code NotFound".
App Service is running and log streams shows the 404.

After some time I noticed the ".deployment" file that is created with command "az bot prepare-deploy". I changed the property "Copy to Output Directory" value to "Copy Always" for this file in Visual Studio, built, zipped, deployed and everything is working.

Just leaving this here in case someone runs into the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp%2Cnewrg#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by samanthagmccormick** [comment]
Also having the same issue after deploying. Messages I send in the Web Chat result in  "couldn't sent. retry" and I get the same error message as @andreschort: "There was an error sending this message to your bot: HTTP status code NotFound". I used the JS / yeoman generator, and I don't have a .deployment file at all in my project...

**Comment by Kaiqb** [comment]
@samanthagmccormick @waqarghani @andreschort - I have asked one of the testers to look into it.

**Comment by samanthagmccormick** [comment]
Thank you so much :)

**Comment by nstejaswini** [comment]
@samanthagmccormick @waqarghani @andreschort - Which version of Azure CLI are you using? ( Make sure you have 2.0.64 version). 
If the version being used is 2.064 and still facing the issue, please specify more details about the error.

@samanthagmccormick - When you use the command prepare-deploy, after pointing to the right directory(in cmd), you will find web.config file created at the location you have pointed. ( For C# it is .deployment file. For JS and TS it is web.config tha gets created)

**Comment by nstejaswini** [comment]
@samanthagmccormick - When you use the command prepare-deploy, after pointing to the right directory(in cmd), you will find web.config file created at the location you have pointed. ( For C# it is .deployment file. For JS and TS it is web.config tha gets created)

**Comment by samanthagmccormick** [comment]
@nstejaswini here is some more info if it helps. I was  finally able to get everything to work after trying the deployment steps for the 4th time and making 2 changes.

My az cli version is 2.0.64. Yesterday, I was using node version 8.11.3, and today tried switching node versions to 10.14.1 after combing through the `template-with-new-rg.json` file and noticing that it uses 10.14.1:

![image](https://user-images.githubusercontent.com/8485124/57473091-4a3b6c00-724c-11e9-9d2b-9d22a2e5b8cf.png)

I also made another change based on this section:

![image](https://user-images.githubusercontent.com/8485124/57473294-bd44e280-724c-11e9-8e81-ed39d2db33f8.png)

Yesterday, I took the project folder containing index.js, zipped it up, and then ran the `az webapp deployment ...`  script from outside of the project folder. This to me is a normal way to go about it and maybe others did this same thing. But, I re-read the section above another time today and decided to go into the project folder, select all its contents and zip those, then make sure I ran the command from inside the project folder where the zipped folder was,  rather than outside it. I think that might be what the section above asks for, but it wasn't intuitive for me to do it that way, even having read the above section.

So -- I'm not sure if either upgrading to node 10.14.1 solved the problem OR changing where I zipped 
 and ran the deployment command, but one of those  fixed it for me and I am finally able to test chat from inside my bot's Test Web Chat in the Azure Portal.

**Comment by nstejaswini** [comment]
@samanthagmccormick That's what the document says. The project file with all the components (make sure that the  index.js/ .csproj  and web.config/.deployment file are present) should be zipped together. Your were facing the error because of this only. The node version was not the problem. Because I have tested it with the node version 8.12.0, it worked fine.

**Comment by ivorb** [comment]
I've added another detail to explain that in the note referenced above - it appears to not be due to the node version, and instead due to the location of zipping. Hope that makes it clearer!
