### ISSUE TITLE
Card Action Title limit of 20 chars ?

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/bot-docs#1141]
When I am providing more than 20 char as the title the Action Button is not visible instead it is displayed as plain text ? Is this a known issue or a limitation ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by nstejaswini** [comment]
@vikramdadwal There is no limitation like that. It will display as a button only without any dependency with the number of characters. Please check the screenshot attached. If you are still facing the problem, please send a screenshot of how it is appearing for you.
![Screenshot (119)](https://user-images.githubusercontent.com/39872221/57904605-0d492800-7891-11e9-9edd-a0c020e0bd41.png)

**Comment by vikramdadwal** [comment]
The code I am using to create the Prompt:

await dialogContext.PromptAsync(dialogId, promptOption, cancellationToken);

where PromptOption is constructed as:

promptOption = new PromptOptions
            {
                Prompt = activity,
                Choices = new List<Choice>()
            };

where one of the choice has title : "Chat With Agent and Submit ticket"

**Scenario 1:** When the char are more than 20 then BOT is displaying as following:

![image](https://user-images.githubusercontent.com/10174566/57943566-306fd980-7889-11e9-8566-48c3e201edc0.png)

Scenario 2: when chars are upto 20

![image](https://user-images.githubusercontent.com/10174566/57943665-7331b180-7889-11e9-93e6-66e21016059a.png)


**Few points to NOTE:**

- Scenario 1 put the suggested action as the Text property of the Activity.

- The prompt activity is an adaptive card which is constructed as following:

var activityToShow = (Activity)MessageFactory.Attachment(AdaptiveCardAttachment.Create(cardContent));

**Comment by emgrol** [comment]
Hi @vikramdadwal, I tried adding strings, 20+ characters in length, to the sample in [the article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp) you referenced, and as you can see below there are no issues:

![image](https://user-images.githubusercontent.com/9682548/62726551-514d5400-b9cc-11e9-86c4-4b11152fe4aa.png)

Since you're using prompts, though, I would recommend looking at the following documents to help you format them:
- [DIalogs library](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0#prompt-options)

- [ChoicePrompt.Style Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.choiceprompt.style?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_Dialogs_ChoicePrompt_Style)

- [ListStyle Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.choices.liststyle?view=botbuilder-dotnet-stable)

**Comment by emgrol** [comment]
You can post any further questions about this issue on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) for more support.

**Comment by ojasmaru** [comment]
I have the same issue. What was done to resolve the issue?

I have posted the question on [Stack Overflow](https://stackoverflow.com/questions/58017710/bot-framework-promptoptions-choices-20-character-limitation)
