### ISSUE TITLE
flow in dialogs

### ISSUE THREAD

**Issue by Unders0n** [MicrosoftDocs/bot-docs#1148]
after done all this steps i noticed that flow in my dialog changed, i've took VirtualAssistant example and simplified it a bit, after doing steps from this page seems like dialog stack is broken and i'm not getting to 2nd step of waterfall after completing 1st step.
Testing locally.
Please tell if need to provide some code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* Sub-service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by JonathanFingold** [comment]
I'm uncertain. Direct Line Speech is in preview, and the Virtual Assistant bot is maintained by another team. @lauren-mills , Is this something your team can field?

**Comment by Unders0n** [comment]
any update guys?

**Comment by lauren-mills** [comment]
A few questions to help me troubleshoot:

- Can you explain what changes you made to the VA project?
- Have you tried your project on other channels and verified it worked correctly?

**Comment by Unders0n** [comment]
@lauren-mills thanks, will fill up this tomorrow. Meanwhile i have noticed i can't find docs on how to exchange secret to token, in examples i see only some call to controll which do that, please clarify that, thanks.

**Comment by Unders0n** [comment]
ok i think i have found a fix for that. I've noticed that dialog stack was broken with
services.AddSingleton<IBotFrameworkHttpAdapter, WebSocketEnabledHttpAdapter>();
but with services.AddSingleton<IBotFrameworkHttpAdapter, DefaultAdapter>(); it was working,
so i copied DefaultAdapter.cs 's code but inherited from WebSocketEnabledHttpAdapter instead of BotFrameworkHttpAdapter and now seems like it's working.
Full code: https://gist.github.com/Unders0n/eb91cf11c0c40b882a81100d56163ac1

Please comment

**Comment by lzc850612** [comment]
Yes you need to use the DefaultAdapter's code because the middleware which is going to guarantee the state of the conversation is automatically saved is AutoSaveStateMiddleware which is configured in DefaultAdapter.cs. If you use services.AddSingleton<IBotFrameworkHttpAdapter,WebSocketEnabledHttpAdapter>(); you're not explicitly saying you're going to use that middleware so the dialog stack won't be saved in every turn.

**Comment by Unders0n** [comment]
@lzc850612 i think that should be added in docs, 'cos saving state is kinda default behavior. 
Also could you reveal on how i can exchange secret to token n direct line speech?
And also i have raised this question: https://stackoverflow.com/questions/56340032/is-new-ms-botbuilder-directline-speech-good-fit-for-call-center-scenario which is also left with no attention, mb you have some thoughts on that? thanks.

**Comment by darrenj** [comment]
@Unders0n - Hi Andrey. We have recently updated the Virtual Assistant template to have Direct-Line speech integrated out of the box with no manual changes whatsoever beyond adding the DL Speech channel. Documentation has been [added](https://github.com/microsoft/botframework-solutions/blob/master/docs/howto/assistant/csharp/speechenablement.md) to reflect this so think we addressed the root cause here.

Also checked that your stackoverflow questions has been answered so think you have everything you need.

Feel free to work with us over on [our repo](https://github.com/microsoft/botframework-solutions) if you have any further questions.
