### ISSUE TITLE
Why is Kudu build advised over uploading prebuilt binaries?

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bot-docs#1169]
It looks like the Bot Framework suggests letting App Service build the bot logic from source using Kudu rather than have the user / CICD upload prebuilt binaries.

Personally I thought the idea of CI/CD was making one deployment package containing binaries that can be configured using appsettings.json. This deployment package could then be distributed to various environments.

This non-standard choice for deployment package creation and the usage of the bot file to store secrets rather than using appsettings + environment variables make this feel a bit uneasy / awkward to me.

Could you please explain why the bot framework seems to deviate from the ASP.Net Core standards,, what the benefits of it are and why we should stick to it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
If you look at the current SDK, we no longer use the bot file, and are back to appsettings etc - so that should alleviate that one concern.

As for uploading prebuilt binaries vs building them in Kudu, this allows for multiple endpoints to modify the existing bot (including through the portal, which I believe is being depreciated). Had Kudu not built the source, editing files through the portal wouldn't have been possible.

If the reasons for using Kudu are going away, there may no longer be a reason to stick with this method of deployment. Please log an issue in the SDK repos, such as https://github.com/Microsoft/botbuilder-dotnet/issues to request this change.

**Comment by hansmbakker** [comment]
About the bot file - I hadn't noticed that (we're using the enterprise bot template which was suddenly deprecated --> no updated example anymore - therefore I didn't see that projects now do not use the bot file anymore)
