### ISSUE TITLE
Create more complete Bot Telemetry section

### ISSUE THREAD

**Issue by scheyal** [MicrosoftDocs/bot-docs#1174]
We need a more complete bot telemetry guidance section. Proposed section Table of Contents:

### Bot Analytics
 
* Introduction: what is it about, how to go about it and the options at high level
* Instrument your application with this telemetry (and/or customize as needed)
* See results as follows:
  * Application Insights in Visual Studio
  * Azure Dashboard (do we have any)
  * Power BI
* Deep dive into conversation analysis techniques for improving bot quality
* Advanced topics (as/if applicable, for example):
  * Attach external consumer for Spark/Tableau…. Other consumers
  * Custom / extended instrumentation

Reference: Current page in review: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&branch=pr-en-us-1504

**Comment by JonathanFingold** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary.
