### ISSUE TITLE
I created the bot in Azure, downloaded, coded and tested with emulator, now I need to deploy to Azure

### ISSUE THREAD

**Issue by jsciandra** [MicrosoftDocs/bot-docs#1178]
You need to think about use cases. You do not document 1 out of 2 possible use cases. Either you start on the local computer and do all this stuff, or you create and download the source code from azure with all the id, resource id and everything defined in azure in advanced. how does this doc address that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=erg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
I'm confused what you're asking. The two use cases I'm getting from your issue are:

1. Make a bot that runs locally, then you want to deploy it (what this article covers)
2. You create your bot in Azure with everything defined in advance, then you download it, make some changes, and want to publish those changes.

Are you asking for details on number 2?

**Comment by RobRoseKnows** [comment]
@ivorb I can't speak for @jsciandra but that's what I'm working on currently and it would be nice to get some details on number 2, especially since the publishing pane in Azure portal links directly to this page.

**Comment by jsciandra** [comment]
I am asking about #2, but I got it to work. I set up continuous integration with bitbucket and kudzu (or whatever). The doc is adamant about deploying before CD will work. Your doc assumes that you started from an empty file on your pc and coded and now need to completely configure the azure env. But I think that the more common use case is to configure the whole thing up in azure and pick echo or whatever bot and then download and modify. I never could get a simple deploy at that point working. Getting CD working, the biggest prob i had was the token connection to bitbucket from a previous bot, like 6 months ago, was creating a bad url for the link to the bitbucket repo when I picked the new repo from the azure build dropdown. It took me a while to notice the badly formed url. I had to disconnect and reconnect bitbucket twice before the repo url showed correctly. there is no way to override it. So, I'm good, but yes, I would say #2 needs as least as much coverage as #1

**Comment by zxyanliu** [comment]
Hi- thanks again for your feedback. 

We have two different docs regarding the two use cases you have mentioned. 
1. if you have a local bot and you want to deploy your bot to Azure, you can read the "deploy a bot" article: 
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg
2. if you already have a bot deployed in Azure and you want to download the code, make changes and publish the changes, you can read the "set up continuous deployment" article:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0

Additionally, you have other options for continuous deployment depending on necessary permissions you may have. This is documented in this article: 
https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment#option-1-use-app-service-kudu-build-server

Since you have got it work and your issue been solved. We will close it at this time. 

We appreciate your valuable feedback on this particular topic. Feel free to open a new issue if you have in the future. 

Thanks.

**Comment by zxyanliu** [comment]
Hi - FYI, for the second use case, you can also try using github to set up continuous deployment. I have tried and verified the content work for me. 

I followed the "set up continuous deployment" article. I deliberately made changes to a basic echo bot. After I set up continuous deployment in github from Azure, I got the change shown in Azure: 

![image](https://user-images.githubusercontent.com/32497439/62177101-8d135a00-b2f8-11e9-8368-822e8e915422.png)

Thanks again and hope it is helpful. 

Best,

**Comment by zxyanliu** [comment]
Hi -FYI
I have been exploring the redeployment topic lately and would like to share what I got: 
1. If you wanted to make changes to your bot frequently, you can set continuous deployment documented in this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0). I have tested and verified the topic using Github to setup continuous deployment covered in this article. 

2. If you only wanted to make changes once in a while, you can follow steps to Retrieve or create necessary IIS/Kudu files, zip up your updated bot project and redeploy to Azure documented in this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0). I have tested this today and got my bot redeployed with success. 

![image](https://user-images.githubusercontent.com/32497439/63554480-6d83e180-c4f2-11e9-8d5a-3ba99be84bf2.png)

I hope it helps.

Yan
