### ISSUE TITLE
deployment steps are not clear

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/bot-docs#1202]
Hello,

I have followed all the steps mentioned above but at the last step when deploying the webapp, I am getting a nice JSON output:

Starting zip deployment. This operation can take a while to complete ...
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2019-06-13T13:14:49.6491874Z",
  "id": "ID",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2019-06-13T13:14:49.6491874Z",
  "log_url": "https://edmspeechtotranslatebot.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "provisioningState": null,
  "received_time": "2019-06-13T13:14:04.3311237Z",
  "site_name": "edmspeechtotranslatebot",
  "start_time": "2019-06-13T13:14:04.6577488Z",
  "status": 4,
  "status_text": "",
  "url": "https://edmspeechtotranslatebot.scm.azurewebsites.net/api/deployments/latest"
}

and in action, no web app is created on the portal. when I see the logs, its so unclear to guess or assume about errors. 

{"Message":"An error has occurred.","ExceptionMessage":"No log found for 'latest'.","ExceptionType":"System.IO.FileNotFoundException","StackTrace":"   at Kudu.Core.Deployment.DeploymentManager.GetLogEntries(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Deployment\\DeploymentManager.cs:line 95\r\n   at Kudu.Services.Deployment.DeploymentController.GetLogEntry(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\DeploymentController.cs:line 375"}

I have no idea now what went wrong. Can you please provide some additional links or information. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by hdg97** [comment]
I believe they don't create logs for you. You have to log things yourself with a logging library (this is my guess, since I've never logged yet. I've also been using these deployments for my application, and got this error as well.) You can go to you channel service to see if there were any errors, but in general, their indication on what is failing is pretty poor. You kind of have to guess what's happening and recheck the instructions to see if you missed an obscure step.

Couple of things you can check is:
Internal server error might mean you forgot to prepare-deploy your app
Unauthorized error might be that you didn't fill in your credentials at the correct places

One big one that confused me a lot, since they changed their wording, is that appSecret in step 2 is the password you created (AtLeastSixteenCharacters_0), and not the password Key that you receive as a json in step 1.

**Comment by ADefWebserver** [comment]
You may find [this article ](http://aihelpwebsite.com/Blog/EntryId/1030/Creating-a-Hello-World-Bot-MS-Bot-Framework-V4-Preview-Edition) helpful. It basically descibes a way to simply create a **Web App Bot** in Azure and then publish your code from Visual Studio to that. Really easy that way, just remember to select the option to _Remove additional files at destination_ otherwise it will _revert back_ to the previous code after 5 minutes when the associated **App Service** (that is created for you and configure for you automatically) restarts.

**Comment by vivekjainAco** [comment]
If I am migrating from the old V4 version to new V4.3 version bot and removed the .bot file and using the appconfig file. 

While follwing the steps, the step "Create Azure resources", needs an template file. where to get this file. I dont have it in my project until now?

**Comment by Kaiqb** [comment]
You can grab the ARM templates from https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.echo-bot/DeploymentTemplates.

**Comment by vivekjainAco** [comment]
I am able to deploy a new bot based on the @ADefWebserver but then speech services are not working on the web chat test window in azure. 

I am tired of this black box deployment procedure. I again created a new SDK v4.3 bot and it works locally and followed all the steps from Bot deployment documentation. It has created an app service, an app service plan, and Bot Channels Registration.

not sure if I shall web chat panel in Bot Channels Registration, well i tried but messages are not sent there. and there is not bot web app created so confuse now. whats going on?

are there any visual snap shots for the bot cli deployment?

**Comment by emgrol** [comment]
There are no snapshots but you may find the instructions in [Deploy your bot article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg) helpful. After following those instructions you should be able to test your bot in Web Chat.

**Comment by Kaiqb** [comment]
If you are trying to use Direct Line Speech, take a look at this [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0). Note that this service is in public preview. If you are still having issues, please log a support ticket on [Stack Overflow.](https://stackoverflow.com/questions/tagged/botframework) Thank you!
