### ISSUE TITLE
Can you please explain how to add new waterfall dialogs to this project?

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#1224]
I've been reading the code for perhaps 2 days now and the documentation perhaps 10 times and I just don't understand it. The code is all over the place. I got authentication to work, but I didn't understand anything. I just changed the app settings file. Now I need to add more dialogs now that I have a user token. I want to add a new Waterfall dialog like allowing users to send a new email or schedule a meeting. Where do I add these waterfall dialogs? Do I make a new DialogComponent class for that? Do I add it in MainDialog.cs? In AuthBot.cs? In DialogBot.cs? I see MainDialog extends LogoutDialog. Does this mean I can only have one dialog to main dialog? I want to add more waterfall dialogs. The code is very confusing and I don't know where to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
@AskYous Agreed that this documentation is very sparse at the moment. I won't get a chance to experiment with the code till next week. I'll flag this for support in the mean time.

**Comment by jwiley84** [comment]
Hey @AskYous! Let's see if we can untangle this for you (and yes, this particular doc is light on the details, mostly because what you ultimate want is in other docs).

Concerning Sample 18.Bot-Authentication:
![image](https://user-images.githubusercontent.com/17333688/60608762-16288700-9d75-11e9-9a5e-a2f06a5847de.png)

These two are going to be the "bot", for lack of better terminology. AuthBot.cs's whole job is to welcome users, and DialogBot.cs's job is to save state changes. Honestly, I can see why you'd be confused, since they could *probably* have been combined into the same class for simplicity. Neither one really hold any dialog logic. AuthBot.cs does send a message, but that's because it's looking for an event, not dialog.

Moving on. 

![image](https://user-images.githubusercontent.com/17333688/60609002-89ca9400-9d75-11e9-9910-db889f8c873a.png)

These are your dialogs for the bot. Any additional changes you want to make to dialogs are going to go in this. 

> I see MainDialog extends LogoutDialog.

It shouldn't. It should extend ComponentDialog. It seems it was written this way to have a "simple" (but confusing) way to handle the 'logout' interruption. In an MVC bot, MainDialog.cs's whole role should be to get the ball rolling in the beginning, and handle wrap up/restarting at the end. Your component dialogs are going to handle the logic. 

For example, you said you want users to be able to login and check email as an example. MainDialog.cs is going to have a waterfall for logging in, and one of the steps is going to be a successful login check. Upon that step succeeding, it will start a new component dialog called EmailCheckerDialog.cs (because I'm super inventive with names) using 

`return await stepContext.BeginDialogAsync(nameof(EmailCheckerDialog), null, cancellationToken);`

If I were to place it, I would put it in like this:

```
private async Task<DialogTurnResult> LoginStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            // Get the token from the previous step. Note that we could also have gotten the
            // token directly from the prompt itself. There is an example of this in the next method.
            var tokenResponse = (TokenResponse)stepContext.Result;
            if (tokenResponse != null)
            {
                await stepContext.Context.SendActivityAsync(MessageFactory.Text("You are now logged in."), cancellationToken);
                return await stepContext.BeginDialogAsync(nameof(EmailCheckerDialog), null, cancellationToken);
            }

            await stepContext.Context.SendActivityAsync(MessageFactory.Text("Login was not successful please try again."), cancellationToken);
            return await stepContext.EndDialogAsync(cancellationToken: cancellationToken);
        }
```

Then in your EmailCheckerDialog.cs component, you could do whatever you needed to do, such as running ANOTHER waterfall to get the information needed from MSGraph (like asking the user for date range, or what kind of emails, or whatever you want really). 

I know I've probably made this clear as mud to you. A good reference to track/verify what I'm going on about is [Create advanced conversation flow using branches and loops](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp). It talks about component dialogs and conversation flow.

**Comment by AskYous** [comment]
Thank you very much @jwiley84.
