### ISSUE TITLE
adding credentials to bot emulator is required if the .bot configuration file is going to be deprecated

### ISSUE THREAD

**Issue by xtianus79** [MicrosoftDocs/bot-docs#1230]
This left my head spinning for a little bit.  However, if you create the bot via azure and the bot credentials are added to the appsettings.json then you will need to add those into the emulator upon running the bot or it won't proceed.  With that said, is there a way to pass along bot configuration microsoftappid and microsoftapppassword to the emulator without doing it manually. for future implementations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Sub-service: **cognitive-services**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
The Emulator, Azure CLI, and the Bot Framework are all a little out of sync on this. At the moment, I think you need to create the .bot file by entering this information in the Emulator itself, by hand.

Unfortunately, the use of a .bot file hasn't made it out of preview, and the docs specifically don't describe its use because it is not stable and may be deprecated.

The Emulator is in a separate project, and you can open this as an issue in the [Bot Emulator repo](https://github.com/Microsoft/BotFramework-Emulator/) to request better integration with the Azure CLI.

**Comment by CoHealer** [comment]
@mdrichardson can you please assist?

**Comment by mdrichardson** [comment]
@xtianus79 	The `.bot` file was used in early V4 and is mostly being deprecated in favor of `appsettings.json`. That being said, you can create one in Emulator through `File > New Bot Configuration`.

![image](https://user-images.githubusercontent.com/40401643/62316761-0f149780-b44d-11e9-9dc6-3afd39b2ec71.png)

This will create a `.bot` file that will allow you to double-click to open the bot in Emulator.

Alternatively, you can also open via URI protocol in the format:

```    
bfemulator://livechat.open?botUrl=url[&msaAppId=id][&msaPassword=pw][&secret=secret]
```
