### ISSUE TITLE
How to run virtual assistant template

### ISSUE THREAD

**Issue by jnaman509** [MicrosoftDocs/bot-docs#1292]
i am trying to run virtual assistant template in my local system. so i want to ask how can i do this without hosting it in azure . currently i don't have any key which is mention in appsetting.json file.

**Comment by jnaman509** [comment]
i am trying to run virtual assistant template in my local system. so i want to ask how can i do this without hosting it in azure . currently i don't have any key which is mention in appsetting.json file.

**Comment by emgrol** [comment]
If you take a look at either the [C#](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md) or [TypeScript](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/typescript/virtualassistant.md) tutorials for creating your first virtual assistant you will find this line:
> The Virtual Assistant requires the following Azure dependencies to run correctly. These are created through an [ARM (Azure Resource Manager)](https://azure.microsoft.com/en-us/features/resource-manager/) script (you can modify this to meet your requirements).

Due to these Azure dependencies you cannot run your virtual assistant locally and instead need to deploy your virtual assistant for it to run correctly.

**Comment by Kaiqb** [comment]
The instructions specific to Virtual Assistant are [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/reference/assistant/deploymentscripts.md).
