### ISSUE TITLE
When appliying these changes the translation middleware stops working

### ISSUE THREAD

**Issue by MichaelBuczek** [MicrosoftDocs/bot-docs#1316]
It might work when used alone, but together with the translation middleware it does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0b8671-359e-6026-fd3a-39331cea73f3
* Version Independent ID: 29bab4ad-243a-fb0a-99ed-d8336a92f648
* Content: [Develop DirectLine Speech Bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/directline-speech-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/directline-speech-bot.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
We'll need to research this. Hopefully, we can get back to you soon.

**Comment by DDEfromOR** [comment]
This may be due to a bug in an earlier version of the NuGet packages that caused middleware to not be set on the streaming adapter. The current packages are available from NuGet (not MyGet) as:
 https://www.nuget.org/packages/Microsoft.Bot.Builder.StreamingExtensions/4.5.1-preview1 (for the bot integration) and https://www.nuget.org/packages/Microsoft.Bot.StreamingExtensions/4.5.1-preview1 (for the library itself). 

Substituting the the bot integration NuGet for the MyGet package referred to in the documentation should be a straight forward upgrade that brings with it a fix for the middleware bug. 

The docs should be getting updated to point to the public preview packages linked above, but I'm not sure what the timeline is.

**Comment by JonathanFingold** [comment]
I have a fix in PR.

**Comment by MichaelBuczek** [comment]
It would be very helpful to have information on what limitations there are in use of multiple languages. E.g. Edge and Chrome read different language settings when performing speech-to-text. Replies in other languages than the one in the setting are muted, so there is no way to speak a translation. In the DirectLine sample I found (https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/directline-speech/csharp_dotnetcore/13.core-bot), the only way to switch languages (e.g. in the translation scenario) is to connect to the bot again, which really messes up state information :-).

Further, i have problems getting the "speak" feature to work. The code above does not generate any speech in the samples I mentioned above, while this code works in webchat (sometimes):

await context.SendActivityAsync(writethis, saythis);

I haven't been able to find any information on how to get this to work with adaptive cards. Not being able to test in the emulator makes life hard :-). I tried the webchat client and the DL client. 

Any pointers are appreciated :-)
