### ISSUE TITLE
Incorrect Formatting in Deployment Docs

### ISSUE THREAD

**Issue by mdrichardson** [MicrosoftDocs/bot-docs#1323]
In [this section](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0#create-an-app-registration), we have this note that could use a formatting fix:

![image](https://user-images.githubusercontent.com/40401643/63109757-c5dd4100-bf3e-11e9-8ef0-2110cc525a40.png)

I would submit the PR myself, but I was the one who submitted the original PR for this and it appears I don't know how to format this correctly. This is what I see in the `.md` file:

![image](https://user-images.githubusercontent.com/40401643/63109870-fc1ac080-bf3e-11e9-8a15-d988d232b8fa.png)

...which looks like it should work, but does not. **Note: We should also remove the semicolon at the end of the command**

If you could point out where my formatting went wrong for the docs, I'd appreciate it so I don't make the same mistake in future PRs.

**Comment by emgrol** [comment]
Hi @mdrichardson, it seems like the command wasn't encased in back quotes (\` character), so it didn't show up as a code block (described further in detail in [this cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)).

I've reformatted that section, you can see the changes in this [PR 1660](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1660).

**Comment by mdrichardson** [comment]
@emgrol Aha! That wasn't [the change that I submitted](https://github.com/MicrosoftDocs/bot-docs/pull/1233/files#diff-2f92b7bf10ac615faea324908b550101R67)...No worries. Probably just lost in translation during the merge from public to private repo.

**Comment by zxyanliu** [comment]
@mdrichardson 
FYI, when it's in the Note box, you can use ' ' instead of ``` wrapping your command. 

Is this helpful?

**Comment by emgrol** [comment]
@mdrichardson, @zxyanliu makes a good point, and I think I found the main issue with your note (which I want to keep as you've formatted it since having the copy button with it makes it easier for the reader)

Tips, notes, warnings, etc. need to be on their own line. When I tried building with your snippet I kept getting a warning about there being an invalid string in the first line of the note. So the note should look like this:
\> [!NOTE] 
\> all of the note's content goes here
\> and on following lines if need be

You can see [PR 1663](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1663) to see how I reformatted the note.

**Comment by mdrichardson** [comment]
@emgrol Makes sense. Good to know!

**Comment by emgrol** [comment]
Closing this now that the formatting is correct, changes will go live tonight.
