### ISSUE TITLE
Why are Activity types mentioned on this page?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1334]
The Activity types section tacked onto the end of the page seems to give very little information about activity types and could be considered misleading. Would it be better to make this page just about entities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53617abe-a774-a211-390b-b2f0261c5bb6
* Version Independent ID: f1533f6c-f340-f838-d95b-ca5b6cd4b6dd
* Content: [Entities and activity types - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/bot-service-activities-entities.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-activities-entities.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by zxyanliu** [comment]
Hi @v-kydela 

Thanks for your feedback. To answer your question: 

Activity types are mentioned on this page because this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs) covers both entities and activity types as the title suggests. 

The "activity types" section actually provides much information if you click the [Activity schema page](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md). The content of activity types is referenced here to avoid duplication. 

See the image below: 

![image](https://user-images.githubusercontent.com/32497439/64276687-5e8f2d00-cefd-11e9-870b-d2d08d78acb6.png)

Does this help? 

Thanks.

Yan

**Comment by v-kydela** [comment]
@zxyanliu - Perhaps you misunderstood me.

I can see that the title of the article is about both entities and activity types but I'm saying that doesn't make any sense because these two things are not closely related. Why are they sharing a page?

If the activity types section just links to another page then it's still not giving a lot of information on this page. We already link to the activity spec directly in the resources section anyway:

![image](https://user-images.githubusercontent.com/41968495/64281784-bbdcab80-cf08-11e9-97ad-1fe72f05a54f.png)

Shouldn't we change this page to just "Entities" instead of "Entities and activity types"?

**Comment by zxyanliu** [comment]
Hi - Kyle,

Thanks for your reply. I will bring this in the meeting tomorrow and get back to you soon. 

Yan

**Comment by zxyanliu** [comment]
Hi @v-kydela 

I believe the title "Entities and activity types" is correct since _Entity_ and _Activity_ are related to each other. 

1.  "Entities are a part of an activity, and provide additional information about the activity or conversation." [Entities and activity types](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs)
2. In the [Bot Framework -- activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md) article, you also see description of "Entity". 

FYI, we have updated some content in the _Activity types_ section in PR #[1716](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1716). The content will be live soon. 

Please let us know if helps.

Best, 

Yan

**Comment by zxyanliu** [comment]
Closing the issue. The content is live. Thanks.
