### ISSUE TITLE
Bot Framework Emulator & Suggested Action 

### ISSUE THREAD

**Issue by thibaultcrouzet** [MicrosoftDocs/bot-docs#1343]
Based on your doc (below) I implemented a suggested actions. 
In the Bot Emulator Framework the text is coming but not the action buttons. 

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-suggested-actions?view=azure-bot-service-3.0

**Comment by v-kydela** [comment]
Hello @thibaultcrouzet - I have just tested the activity in that document, replacing the `from`, `conversation`, `recipient`, and `replyToId` fields with applicable values, and also using the correct service URL (which should be an ngrok URL in the case of Emulator) and my own bearer token, and it works just fine. The suggested actions appear as expected. I would like to help, but I need some more information from you:

1. Please provide the HTTP request you are sending (though obscure the bearer token)
2. Please provide screenshots of what you're seeing in Emulator
3. Please tell me what version of Emulator you're using
4. Please let me know what other requests you're sending

Right now, my best guess is that you're sending an activity to the bot after the activity with the suggested actions, which would make the suggested actions disappear.

**Comment by v-kydela** [comment]
Hi @thibaultcrouzet - Are you still working on this?

**Comment by thibaultcrouzet** [comment]
@v-kydela yes

1. I use ngrok 

2.
![image](https://user-images.githubusercontent.com/11459121/64607239-656be300-d3c8-11e9-9b35-343d4dc6f5c2.png)


3. Version 4.5.2 (4.5.2.71281) Mac
4. I used the example that you provided in JSON here : https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-3.0#adaptive-card

you can see that the buttons are missing in the emulator

**Comment by v-kydela** [comment]
@thibaultcrouzet - From the screenshot, it looks like the user has sent one message to the bot and then the bot sent a typing activity and four message activities. Are your suggested actions in the message that says "hello User" or one of the Adaptive Card messages?

**Comment by thibaultcrouzet** [comment]
@v-kydela like I explained in the beginning in _the Bot Emulator Framework the text is coming but not the action buttons_ in the Adaptive Card. 

I don't see any of the action buttons in the Framework Emulator from the JSON below :

                "actions": [
                    {
                        "type": "Action.Http",
                        "method": "POST",
                        "url": "http://foo.com",
                        "title": "Snooze"
                    },
                    {
                        "type": "Action.Http",
                        "method": "POST",
                        "url": "http://foo.com",
                        "title": "I'll be late"
                    },
                    {
                        "type": "Action.Http",
                        "method": "POST",
                        "url": "http://foo.com",
                        "title": "Dismiss"
                    }
                ]

This below should be the result based on your documentation : 

![image](https://user-images.githubusercontent.com/11459121/64684374-4b440a80-d485-11e9-9e86-bb331286d172.png)

But this is what I get :

![image](https://user-images.githubusercontent.com/11459121/64684666-d1605100-d485-11e9-9ea9-fbf591b64e66.png)

**Comment by v-kydela** [comment]
@thibaultcrouzet - Thank you for the clarification. I understand the problem now. Allow me to explain.

Suggested actions are a term used in the Bot Framework to refer to some kind of temporary button that disappears as soon as a message is sent. They're usually used to automatically send a text message without the user having to type it. Because the Bot Framework connects to many different channels with their own messaging platforms and possibly their own suggested action implementations, the Bot Framework tries to unify these potentially different channel-specific features under the umbrella of suggested actions. For example, in Facebook Messenger the feature is called quick replies and they might look like this:

![image](https://user-images.githubusercontent.com/41968495/64713524-dc10eb00-d471-11e9-9ec8-5afaf7501cac.png)

As you can see, suggested actions exist outside of cards. What you want to do is add actions to an Adaptive Card, but these Adaptive Card actions are different from suggested actions. You have the right idea, but unfortunately there is a problem with the Adaptive Cards document you linked. I have logged that as an issue here: https://github.com/MicrosoftDocs/bot-docs/issues/1346

The problem is that Adaptive Cards don't support [`Action.Http`](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#actionhttp). There's something called Outlook Actionable Messages that's based on Adaptive Cards, and that's where `Action.Http` comes from. You can see the list of supported actions in the [Adaptive Cards schema explorer](https://adaptivecards.io/explorer/).

If you really want the client application to trigger an HTTP request then you could try `Action.OpenUrl` and link to some page that makes the request. But what I normally recommend is `Action.Submit` which sends a message to your bot, because your bot can respond to the message by making whatever HTTP requests you want. For more information, see [my latest blog post](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/).

Does this resolve your issue?

**Comment by thibaultcrouzet** [comment]
@v-kydela yes it does. thanks!

**Comment by thibaultcrouzet** [comment]
@v-kydela yes it does. thanks!
