### ISSUE TITLE
Unable to send video attachment through Line Channel

### ISSUE THREAD

**Issue by PeterChen1105** [MicrosoftDocs/bot-docs#1390]
I tried to connect the Line App Channel with the Microsoft Bot Framework. When I was testing the sending video attachment functionality, it works well in the Web Chat & local environment.

![Bot - Web Chat](https://user-images.githubusercontent.com/53604754/67545366-8c962e00-f744-11e9-9223-b5a2a29e5e81.png)

However, when I tested it through Line Channel, it generates a channel-specific error.

![Bot - Line Channel Error](https://user-images.githubusercontent.com/53604754/67545489-00383b00-f745-11e9-902f-03b2a20c9eaf.png)

Also, the video could not send through and no error message was returned to the user.

![Bot - Line Channel](https://user-images.githubusercontent.com/53604754/67545541-34abf700-f745-11e9-9db2-28b7bf9825cd.PNG)

Line App does support sending video attachment through the bot, and the function should be encapsulated in the bot framework. Could you please help fix the issue? Thanks.

**Comment by stevkan** [comment]
@PeterChen1105, I'll start attempting to repro this issue, however can you post the relevant code you are using for producing and sending the video attachment?

**Comment by stevkan** [comment]
Can you tell me which version of Botbuilder you have installed?

I wasn't able to repro the error you generated. However, I was able to get the video to display in Line. I fudged and dumbed-down some of the internals of the function calls (for simplicity and because I'm not connected to your systems), but otherwise tried to replicate your flow. The only real difference I noted is my inclusion of the `thumbnailUrl` property in `getInternetAttachment()`.

I don't know if you have that property assigned, but I do know the docs example (demonstrating attaching an image) does not include it. Technically, the `thumbnailUrl` is an optional BotFramework property but does appear to be required for sending a video to Line. When I leave that property out, I get an error.

Here is my code, for comparison's sake.

Assigns `videoOwner` to video and image file extensions passing them to `sendVideo()`
```js
async videoStep ( stepContext ) {
  // Assign the video to be assessed.
  const studentId = 'baby_dog15';
  const index = null;
  const videoOwner = await getVideoOwner(studentId, index);
  // Get the video from Firebase and send to the user.
  await sendVideo(stepContext.context, `${videoOwner}.mp4`, `${videoOwner}.jpg`);
  return { status: DialogTurnStatus.waiting }
}
```

Generates video and image URLs passing them to `getInternetAttachment()`
```js
async function sendVideo(turnContext, videoName, imageName) {
  // Send the video back to the user.
  const signedUrl = await getVideoUrl(videoName);
  const imageUrl = await getImageUrl(imageName);
  const reply = { type: ActivityTypes.Message };
  reply.attachments = [await getInternetAttachment(signedUrl, imageUrl)];
  await turnContext.sendActivity(reply);
}
```

Obviously, more happens here, but keeping it super simple.
```js
async function getVideoOwner(id, index) {
  if (id) {
    return id
  }
}
```

Ditto
```js
async function getVideoUrl(videoName) {
  if (videoName) {
    return `https://static.videezy.com/system/resources/previews/000/037/961/original/${videoName}`
  }
}
```

Ditto
```js
async function getImageUrl(imageName) {
  if (imageName) {
    return `https://static.videezy.com/system/resources/thumbnails/000/037/961/small/${imageName}`
  }
}
```

Assigns video and image URLs to `contentUrl` and `thumbnailUrl` properties. `contentType` is set to `video/mpeg`.
```js
function getInternetAttachment(signedUrl, imageUrl) {
  // NOTE: The contentUrl must be HTTPS.
  return {
      name: 'Puppies!',
      contentType: 'video/mpeg',
      contentUrl: `${signedUrl}`,
      thumbnailUrl: `${imageUrl}`
  };
}
```

![image](https://user-images.githubusercontent.com/18403946/68629956-8b7e3400-049a-11ea-9762-7090d31749d5.png)

![image](https://user-images.githubusercontent.com/18403946/68629961-8de08e00-049a-11ea-8fba-ebc1a8948058.png)

**Comment by PeterChen1105** [comment]
@stevkan Hi Steven, thanks for your response!

I used the BotBuilder version 4.5.1 for development, and yes, I didn't include the` thumbnailUrl` property in the `getInternetAttachment()` function. After I add the property into my code, the video can be sent through successfully.

So apparently this property is compulsory for the Line Channel, while not required for most of the other channels (including connecting WeChat through Direct Line, Web Chat, Facebook Messenger which I have tested to be working).

Many thanks again and I will close this issue now.
