### ISSUE TITLE
After clicking on DirectLine Speech: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by ashoksamal6363** [MicrosoftDocs/bot-docs#1419]
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by ahotrod** [comment]
Now get a blank page.

**Comment by ashoksamal6363** [comment]
how to fix it?

**Comment by nisheetjain** [comment]
Thanks for reporting this issue @ashoksamal6363 and sorry for a delayed response here.  This is known issue where some customers see a blank page in Internet explorer and we are working on a fix to address this soon. In the meantime, can you check this behavior in other browsers (Chrome/Firefox etc.)?

**Comment by naday84** [comment]
Im getting a blank page across Edge and IE, while on chrome Im getting "Something went wrong."! what should I do?

**Comment by stevkan** [comment]
May be related to #1475

**Comment by stevkan** [comment]
@ashoksamal6363, @ahotrod, @naday84, if you open the developer's console and then try and connect are you receiving any errors?

If your Web Chat code does not include the following error handler, can you add it and list any additional errors you may be receiving?

```js
<script>
 ( async function () {
    [...]
  } ) ().catch( err => console.error( err ) );
</script>
```

After you've checked for any errors (these will be helpful in determining a solution), a suggested temporary workaround can be found [here](https://github.com/MicrosoftDocs/bot-docs/issues/1475#issuecomment-575829858). I have yet to test it and will leave a comment when I do, but it might be worth checking out and testing for yourselves.

**Comment by stevkan** [comment]
@ashoksamal6363, it appears I completely misunderstood what your question/issue was. There was a known bug (I don't know if it is the same @nisheetjain is referencing) around the URL length that opened the Direct Line Speech blade.

In short, the URL contains a token parameter housing the user's token. This token includes the user's various claims within it (i.e. groups you belong to, permissions, etc.). For users with many claims, the token is longer. The problem here is the URL is bumping up against a length limit. The result is the page not opening or, rather, opening as a blank page.

I don't know if this is still an issue for you. However, in the mean time, a possible workaround is to review the teams, groups, permissions, etc., that are assigned to you and remove or consolidate those that you can. Another option is to create a new user that doesn't have as many claims against it and test if that user account can access the page.

Given the time that has passed on this issue, I'm going to close this. However, if the issue persists or you have new information to provide, please feel free to re-open.

**Comment by mdrichardson** [comment]
Closing per @stevkan
