### ISSUE TITLE
Visual studo 2019

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/bot-docs#1421]
This page could use some updates for Visual studio 2019 mainly around the project creation section.  I am also assuming this can be downloaded via the .net core cli "Install BotBuilderVSIX.vsix"

More information about how to install the emulator and where to get the install needs to be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668ed00-c579-8520-c30f-6008ff4bf9d1
* Version Independent ID: a1d437ab-faa9-fbfa-d380-d1e4b36fdd8e
* Content: [Create a bot with the Bot Framework SDK for .NET - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/dotnet/bot-builder-dotnet-sdk-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/dotnet/bot-builder-dotnet-sdk-quickstart.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by WashingtonKayaker** [comment]
Thank you @LindaLawton for taking the time to report these issues.  I have updated the project creation section of this [article](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0#create-a-bot) to use Visual Studio 2019 instead of 2017.  Regarding the emulator, the link was incorrect, once clicking on the `Bot Framework Emulator` link in the Prerequisites, you can now scroll down to the readme which will give instructions on downloading the emulator. 

Regarding your question on installing the template: Yes, you can install the Bot Framework SDK v4 template using .Net Core CLI. See [Custom templates](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#installing-a-template) for details.
