### ISSUE TITLE
Bot doesn't work when I try to deploy it on Azure 

### ISSUE THREAD

**Issue by PaulienBuskens** [MicrosoftDocs/bot-docs#1463]
I followed the entire Tutorial but when I try to deploy the bot it didn't work.
To try a different approach I created a bot sample account through Azure with Web App Bot. I downloaded the source code of the sample project and found that there where a lot of files missing in de project that I created through this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript#feedback)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by jwiley84** [comment]
Hi @PaulienBuskens!

Can you outline what files were different?

**Comment by PaulienBuskens** [comment]
Hi,

This where the files that I got after following the documentation.

[cid:image003.png@01D5AE76.0EB4C6C0]

This was more or less the files I got from the demo project I downloaded from Azure. A few files changed because I am using the project.
[cid:image005.png@01D5AE76.0EB4C6C0]

Greetings

Paulien

**Comment by PaulienBuskens** [comment]
structure documentation
![structureDocs](https://user-images.githubusercontent.com/32159110/70421196-a5933e00-1a69-11ea-9230-975ebaea7ffd.png)

structure azure demo
![StuctureDemo](https://user-images.githubusercontent.com/32159110/70421216-af1ca600-1a69-11ea-990d-0bb7903d4986.png)

**Comment by v-kydela** [comment]
@PaulienBuskens - That tutorial has a few possible paths to take. I presume from your screenshots that you've chosen JavaScript, but you haven't given any other information like the parameters you've passed into Yeoman or the deployment template you've chosen or any of the values you've passed into the AZ CLI commands. However, I still think I know what's going on.

The deployment process stores your app ID and password in environment variables on the server, but then these environment variables get overwritten by your .env file. You can fix your problem either by including the app ID and password in the .env file or by deleting the .env file.

@Kaiqb - I'm assigning this to you because this is a documentation bug. The tutorial links to a page about migrating from a bot file to a .env file but it gives no indication that you have to do anything with the .env file if you're not migrating and people have no reason to follow that link if they're starting from scratch and therefore don't have a bot file to migrate from.

**Comment by vamboda** [comment]
This tutorial has some serious issues. Please fix it soon...

**Comment by v-kydela** [comment]
@Kaiqb - Have you looked at this?

**Comment by vamboda** [comment]
I found the issue. Azure cli version I am using is not the latest one. The
version I had was 2.0.6. Can we add a note to use latest azure cli with
this link:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest,
if folks are having issues with azure cli deployment commands.

After doing the upgrade, things worked without any issues, at-least for
deployment of preexisting RG template with new app service plan for bots
deployment.

**Comment by mmiele** [comment]
A note added to the article. It will be in the next published documentation.
