### ISSUE TITLE
When testing the Bot authentication example in Emulator getting different token 

### ISSUE THREAD

**Issue by geethabalasubramanian** [MicrosoftDocs/bot-docs#1503]
For eg : We are expecting the access token as follows "eyJ0eXAiOiJKV1QiLCJub25jZSI6InVWZTlnZWRlWV8xRFU1cXJaYzZLQjd3cUZZMVdoeG9GMGNwSXNJSDdIbVkiLCJhbGciOiJSUzI1NiIsIng1dCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSIsImtpZCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMThiZGI0ZS04MjgwLTRhNjEtYTI2Ny1jMjFiNTRlYjlmNTgvIiwiaWF0IjoxNTc4MzkxNDk3LCJuYmYiOjE1NzgzOTE0OTcsImV4cCI6MTU3ODM5NTM5NywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyVmdZS2hLZE9wYjRueGV6Q2J6enBldHhjZmk3Qmg2SDA4UHJkVE43NmdzRjJIODdBa0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik1pY3Jvc29mdCBHcmFwaCBBUEkgTVNUZWFtcyBBY2Nlc3MiLCJhcHBpZCI6IjBiZjcyY2RmLWZkZWQtNDUyZi05MTEyLTkwZjMxOGE4ZTFjNSIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoiVXNlciIsImdpdmVuX25hbWUiOiJUZXN0IiwiaXBhZGRyIjoiMS42LjY2LjIxOCIsIm5hbWUiOiJUZXN0IFVzZXIiLCJvaWQiOiI2ZmI3Y2NjYy1lMDYwLTRmMDQtYjRmNC0zNDYyNjhhYmViODIiLCJwbGF0ZiI6IjMiLCJwdWlkIjoiMTAwMzdGRkU5OUMwOTQ4NCIsInNjcCI6IlVzZXIuUmVhZCBvcGVuaWQgb2ZmbGluZV9hY2Nlc3MiLCJzdWIiOiJXc253Y0Jxai13ejlSLWFkdUdQcTk1aWMtWVJncmZPYlNsVW1wYy1TMG1NIiwidGlkIjoiMDE4YmRiNGUtODI4MC00YTYxLWEyNjctYzIxYjU0ZWI5ZjU4IiwidW5pcXVlX25hbWUiOiJUZXN0VXNlckBBWkNvbGxhYm9yYXRpb25UU1Qub25taWNyb3NvZnQuY29tIiwidXBuIjoiVGVzdFVzZXJAQVpDb2xsYWJvcmF0aW9uVFNULm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImJtV2VWT3FwMFVhc21LSk80WmFXQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfdGNkdCI6MTM2MDQwOTk0M30.WXxqTTdCe-mqpD0yHuue_CXW2QRJGy5u-fKv6vKCwn8ZJQh0ac0MdWGqdrVNwHtvkccs6LeYcTWirTfNQCjJ_BNLijjs1XgEtmpiHqEvznmGpR-AtZM6gTXz-uUF172XFV6QWgqbApsFfY4carUjLCbpDUXd4mYtKdg1-Dt-RoV2w84fCVQUB_A-QzU3F4aHvuvMP6IxSipnCH2ZmJ7a8iDNL9BNGkJHN7LV30T0B_9BxHRuQ1j-YkphhFpk1d2FbBE8JlqNQ79GSglRb7FGAB_Lk4Yeikvj3SsusrdCEYgB0PIwNq7P__7KI4RgFwBPJ7pg24NlJ6Dx91och_xy3A". But I am getting an access token like this "emulatedToken_e9b3f070-32d8-11ea-a7e5-ff06ee60d958". Is this an error? Kindly help me in this regard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#bot-authentication-example)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by anusharavindrar** [comment]
@geethabalasubramanian going by the token which is getting generated for you, it seems like the Emulator has fallen back to providing you with the emulated token instead of a genuine token from the token service. 

- This basically happens when the Emulator fails to generate a valid OAuth signin link. The reason is usually due to an incorrect path to ngrok in the settings page. Can you please verify if the ngrok is correctly installed and points to the ngrok executable in the emulator settings?

![image](https://user-images.githubusercontent.com/48731427/72193020-9a129a00-33bc-11ea-8c9b-6710527fe594.png)

- Also, when you get the emulated token, if you check the logs on the right, it would highlight the error in red stating 'Failed to connect to ngrok instance for Oauth postback URL: Error: Could not find ngrok executable at path.......'

![image](https://user-images.githubusercontent.com/48731427/72193502-b0215a00-33be-11ea-9600-e5247724b6d5.png)

**Comment by geethabalasubramanian** [comment]
@anusharavindrar, I have configured the ngrok, now I am not getting the error that "failed to connect to ngrok instance .... " is not coming. Instead I am getting another error as follows:

[12:20:32]Unauthorized
[12:20:32]Falling back to emulated OAuth token.

And then token is generated as in above screenshot that you have posted

**Comment by geethabalasubramanian** [comment]
@anusharavindrar, I able to get proper access token now. I missed to add "MicrosoftAppId and MicrosoftAppPassword" in .env file and also requesting any user who are getting this similar error to check whether the name provided in the connectionName is created in the same bot service.

@anusharavindrar, I request you to close this issue as it is resolved

**Comment by anusharavindrar** [comment]
Glad that you were able to resolve the issue. Closing this as resolved.
