### ISSUE TITLE
Message delivery order mismatch

### ISSUE THREAD

**Issue by dimovskidamjan** [MicrosoftDocs/bot-docs#1540]
I'm trying to indicate to my users the status of a message sent to the bot service, by marking it undelivered/delivered in the UI. I'm basing this status on the response from the API for sending activities to the bot, once the call is complete the message gets a message id and I add that message as undelivered to the UI.

However, I've noticed that once I send a message to the bot using the API, the bot responds on the web socket that it received the message before the actual message sending request completes, i.e. at the point the socket is notified that the message has been delivered the message doesn't have a message id yet so I cannot find the message in the UI and update it's delivery status.

Is this behavior by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e4dd44-9bfc-14b1-cfd4-d37d500b1877
* Version Independent ID: 965c2c94-8cf1-fbf0-c321-547a90449382
* Content: [Send an activity the bot - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by mdrichardson** [comment]
@dimovskidamjan I don't *believe* that's by design, as it would behave differently than bots using polling. I'll check with the dev team on that.

In the meantime, are you sure that the message you're receiving is the response to the message and not one of [the other response types](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-4.0#receive-messages)?

Can you provide problematic conversation IDs so that I can look into this on the backend?

**Comment by mdrichardson** [comment]
@dimovskidamjan Also, I just tested this myself and am not receiving any kind of response on the WebSocket until the full activity is returned; I tested this with both Node and C# bots.

Perhaps your bot is using `wss.Send()`? That could be the issue as activities must be sent with a HTTP POST.

**Comment by mdrichardson** [comment]
@dimovskidamjan Are you still experiencing this issue?
