### ISSUE TITLE
How do you set conversation account properties?

### ISSUE THREAD

**Issue by liiamjones** [MicrosoftDocs/bot-docs#1545]
I have the following code in a class RootDialog. where stepContext is of type WaterfallStepContext.

var tenantId = stepContext.Context.Activity.Conversation.TenantId

 I then have the following test code

            var client = new DialogTestClient(Channels.Msteams, RootDialog);

            var res = await client.SendActivityAsync&lt;IMessageActivity&gt;(new Activity
            {
                Text = "xys",
                Conversation = new ConversationAccount
                {
                    TenantId = "f7af6be0-1017-4a4e-8e81-5325b780ef98"
                }
            });

The text is coming though, but the whole Conversation property is not being set and remains the default test one where id="conversation1" and type = "convo1"

How can i set this, i need to be able to inject a tenantId into the context for testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afcaa01f-5e9c-8b11-9dbe-9f9740a45397
* Version Independent ID: b24363df-987f-75c3-a8b8-eab8509aa13c
* Content: [Unit test bots - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/unit-test-bots.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/unit-test-bots.md)
* Service: **bot-service**
* GitHub Login: @gabog
* Microsoft Alias: **ggilaber**

**Comment by mdrichardson** [comment]
@liiamjones 

This is happening because the Activity properties [get overwritten](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Testing/DialogTestClient.cs#L90) by [TestAdapter](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs).

To prevent this, you need to use [the other DialogTestClient constructor](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Testing/DialogTestClient.cs#L56), which will need a [TestAdapter with the appropriate constructor](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs#L57):

```csharp
var conversationReference = new ConversationReference........
var testAdapter = new TestAdapter(conversationReference);

var client = new DialogTestClient(testAdapter, RootDialog);
```

[Here's the constructor for ConversationReference](https://github.com/microsoft/botbuilder-dotnet/blob/89817b6b8db42726c9ffcf82bf40b4e66592b84f/libraries/Microsoft.Bot.Schema/ConversationReference.cs#L41)

**Comment by liiamjones** [comment]
Thanks, this has solved my problem.
