### ISSUE TITLE
Native mobile app example

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1597]
Is there any example of the Native mobile app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d63dfde8-e0f4-7607-ed47-9a3eeefb42a1
* Version Independent ID: e7f8c59b-78ef-79c5-73f2-672fbe5ab7d9
* Content: [Embed a bot in an app - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-embed-app?view=azure-bot-service-4.0#creating-a-cross-platform-mobile-app-that-runs-a-bot)
* Content Source: [articles/bot-service-design-pattern-embed-app.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-design-pattern-embed-app.md)
* Service: **bot-service**
* GitHub Login: @matvelloso
* Microsoft Alias: **mateusv**

**Comment by jwiley84** [comment]
There is no example for a native app because of how broad the concept is. For example, how to code a bot for a java-based android app would look different the objective-c based ones for ios. 

The underlying concepts for both the examples above would the be same, however. A native app is going to need a handbuilt 'channel', and to enable communications using directline. The directline documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts?view=azure-bot-service-4.0) explains how to use the directline, and it would be up to the app developer to code the calls to the API.
