### ISSUE TITLE
Incorrect Chinese text render on Dialog

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/bot-docs#1599]
**Describe the bug**

Our bot uses dialog to ask users to fill data. Chinese text doesn't properly show whereas English text renders correctly. The same Chinese text is rendering correctly on message as well.

Please see below attachment for details:
![image](https://user-images.githubusercontent.com/1460168/76589993-3a378d00-64ec-11ea-858e-f38073e9dc07.png)

![image](https://user-images.githubusercontent.com/1460168/76590006-43c0f500-64ec-11ea-91f2-b926e00afa3a.png)

I tested on Mac OS/Chrome browser, Mac OS/Native app.

Any help?

**Comment by JonathanFingold** [comment]
@baole - This appears to be an issue in the SDK. Please open this in the appropriate repo for the language you're using:
- C#: https://github.com/Microsoft/BotBuilder-dotnet
- JavaScript: https://github.com/Microsoft/BotBuilder-js
- Python: https://github.com/Microsoft/BotBuilder-python

**Comment by baole** [comment]
I'm using REST API. Where should I report it?

**Comment by JonathanFingold** [comment]
For the REST API, try https://github.com/microsoft/botframework-sdk.

If they are unresponsive, let me know, and I'll prod someone.

Thanks

**Comment by v-kydela** [comment]
@JonathanFingold - The SDK repo is for DCR's only. No bugs or how-to questions.

REST API bugs can be reported in the [services repo](https://github.com/microsoft/BotFramework-Services/issues), but this is likely not an issue with the REST API. Since this is most likely a channel issue, it should be reported through Teams.
