### ISSUE TITLE
Just Advise, Not Bug: Change "Documentation Example" -> "cURL"

### ISSUE THREAD

**Issue by aecceyhan** [MicrosoftDocs/bot-docs#1665]
When I copy http example from (https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0) it is not copy as cURL

![image](https://user-images.githubusercontent.com/17556123/79389792-55783b00-7f77-11ea-9e28-5d91a06c0cb3.png)

if you change this thing to curl command we can just basically copy-paste to postman

![image](https://user-images.githubusercontent.com/17556123/79390242-067ed580-7f78-11ea-8eb4-fdaeed5f85ec.png)

**Comment by erenakbltt** [comment]
Yes, I agree. If the documentation have a cURL string, anyone can develop their bots much faster

**Comment by emgrol** [comment]
Hi @aecceyhan, thanks for the suggestion. We do have REST docs but recommend developers work with the available SDKs in [C#](https://github.com/microsoft/botbuilder-dotnet), [Javascript](https://github.com/microsoft/botbuilder-js), or [Python](https://github.com/microsoft/botbuilder-python). Closing now since no further work is needed for this issue.
