### ISSUE TITLE
How do I set up twillio for two phone numbers long one and short code?

### ISSUE THREAD

**Issue by turbozapekanka** [MicrosoftDocs/bot-docs#1735]
Instructions only show how to connect to a long number.
I need to connect bot to both long number and short code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b76e08-962a-2a8e-2453-87fb917d68ec
* Version Independent ID: 937798fb-8f76-683c-e146-55dcd79622e1
* Content: [Connect a bot to Twilio - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-twilio.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-twilio.md)
* Service: **bot-service**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by turbozapekanka** [comment]
Consider Short code as just another phone number. So the question is: How do I connect twillio to multiple phone numbers?

**Comment by stevkan** [comment]
@turbozapekanka, is this still an issue you are needing help resolving?

**Comment by turbozapekanka** [comment]
Yes it would be nice to have two (or more) numbers linked to the same bot

**Comment by stevkan** [comment]
@turbozapekanka, unfortunately, due to costs for setting up a Twilio short code, this isn't something that I can test. That being said, this wouldn't be possible via a single bot registration as the Channel only allows for connecting one set of Twilio credentials.

However, it _may_ be possible to set up a bot + skill that are interconnected where one is configured to a Twilio long code and the other is configured to a Twilio short code. You can read about Skill bots [here](https://docs.microsoft.com/en-us/azure/bot-service/skills-conceptual?view=azure-bot-service-4.0). While it may require some additional elbow grease to get fully set up, in theory, there is no reason this shouldn't work.

Per the original question, closing this as resolved.
