### ISSUE TITLE
Alexa certification

### ISSUE THREAD

**Issue by TurinTur** [MicrosoftDocs/bot-docs#1762]
I wanted to ask if the steps explained here are good enough to actually certify the alexa skill that is connected to the MS bot created. Which would be the whole point, to actually being able to publish it to the market. 
Because I'm trying to do it right now, connecting it to the endpoint provided by my bot in azure and all that, and I'm finding some problems. Amazon denied the certification of a small skill I'm developing, saying things like:

_"User: "Alexa, open tele assistance"
Skill: "Hello and welcome!" and the session remains open."_

or 
_3.	The skill did not complete the core functionality using the customer facing information. 
Steps To Reproduce:
User: "Alexa, open tele assistance"
Skill: "Hello and welcome!"
User: "hi how are you"
Skill: "I'm fine thanks" and the session remains open._

Please note that the skill's only intent 'phrase' has slot values which is irrelevant to the skill's functionality. Hence its unable to achieve the core functionality of the skill. 

I'm worried with the 'and the session remains open'. I'm not sure if they are expecting me to close the current session by sending a json or something like that. Also in that second step, they seem to complain for the use of the slot 'phrase', that in this doc it's being used to transfer the entire sentence by to our bot. 

Finally, using the json sample you provided, there is no cancel Intent:
_"Please note that the skill must end the session with a valid response when users say "cancel"."_

Could it be that Amazon has put more restrictive process in the last months?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c24dc268-76db-f9d6-472f-4859a005792c
* Version Independent ID: 8279092d-0e86-c15b-89cb-8759eb25450d
* Content: [Connect a bot to Alexa - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-alexa.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-alexa.md)
* Service: **bot-service**
* GitHub Login: @NickEricson
* Microsoft Alias: **kamrani**

**Comment by NickEricson** [comment]
@garypretty for some of the questions.

Hi TurinTur, I'll answer some questions and we may need to follow up for some others.
_The session being left open_
Currently the session remains open by default. We will change that with the next release to close it by default - that should be deployed next week (there potentially could be delayed due to things outside our control).

_The cancel intent_
Alexa can send AMAZON.StopIntent intents to your bot. The channel will transform these into and EndOfConversation activity. Are you seeing these?

_other_
One interesting thing about this channel is that it is based on this adapter (here is the mapping code to/from Alexa messages):

https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs

We are currently running an older version but will be updating to the latest (4.9.1) version this week. Here 

https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Alexa#customising-your-conversation

is some additional regarding the transformation logic that may be useful.

**Comment by JonathanFingold** [comment]
Questions can be posted at [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) using the `botframework` tag. Please note that Stack Overflow has guidelines such as requiring a descriptive title, a complete and concise problem statement, and sufficient details to reproduce your issue. Feature requests or overly broad questions are off-topic; new users should visit the Stack Overflow Help Center for more details.
