### ISSUE TITLE
Slack scopes

### ISSUE THREAD

**Issue by MattPeterson1** [MicrosoftDocs/bot-docs#1831]
This page needs to be updated for granular Slack scopes:  https://api.slack.com/scopes

What scopes do I need to configure in Slack to use Azure Bot Service Slack Channel?  What Scopes do I need to configure to use the Slack Adapter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Connect a bot to Slack - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @arturl
* Microsoft Alias: **arturl**

**Comment by JonathanFingold** [comment]
@MattPeterson1 - I'm asking the team. I'll forward along the information (once I have it) and update the article.

**Comment by JonathanFingold** [comment]
As you add events in Slack, it lists the scopes you need to request. The scopes you need will depend on the events you subscribe to and how you intend to respond to them.

It looks like you'll need the following OAuth scopes if you follow the instructions in the Slack channel article:
- channels:history
- groups:history
- groups:read
- im:history
- mpim:history

**Comment by danwkennedy** [comment]
@JonathanFingold Do you know if we can choose subsets of scope? My admins are leary of giving a bot `*:history` scope since that allows it to read every message we have on Slack. However, they are willing to allow `app_mentions:read` in which case the bot will be alerted if it's been mentioned in a Slack message. That's perfectly fine for our flow but the docs seem to imply a hard requirement on the scopes you listed here:

>
- channels:history
- groups:history
- groups:read
- im:history
- mpim:history

We might also be able to allow the `im:history` and `mpim:history` since that requires the user to explicitely add the bot but I'm mainly trying to get something off the ground right now.

**Comment by mmiele** [comment]
@danwkennedy Hopefully what @JonathanFingold said helped addressing the issue. In addition, take a look at this article form the Slack documentation: [Understanding OAuth scopes for Bots](https://api.slack.com/tutorials/understanding-oauth-scopes-bot).

**Comment by mmiele** [comment]
The fix will be available in the next documentation update.
