### ISSUE TITLE
Connection to Cosmos DB may barf during development.

### ISSUE THREAD

**Issue by Craigmeister68** [MicrosoftDocs/bot-docs#1900]
Greetings, 
It may be helpful to add a section or link in this page regarding Cosmos DB connection policy. The default connection policy for Cosmos DB SDK v3 is direct, TCP mode which requires certain ports to be open. If developing from local device and those ports are blocked on your firewall, you'll get an 'AccessDenied' socket exception. Adding a setting for gateway mode allows connectivity over port 443. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary.
