### ISSUE TITLE
Direct Line extensions: now GA, no longer in preview

### ISSUE THREAD

**Issue by JonathanFingold** [MicrosoftDocs/bot-docs#1902]
- [ ] https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline?view=azure-bot-service-4.0
- [ ] https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0

**Comment by mmiele** [comment]
The C# client for DL-ASE can't be made GA due to a dependency on a package that is in the process of changing hands from the service team to SDK team. There is no up to date version of the package published today and no means to create a working C# client without additional hurdles we don't want to point people to. 
Eric and Daniel are working on getting an up to date package published soon.

**Comment by mmiele** [comment]
This Issue will not be solved until DL-ASE is GA.
Repurposing [PRr#2392](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2392)

**Comment by mmiele** [comment]
Fixed as per PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2451.
