### ISSUE TITLE
Misleading errors

### ISSUE THREAD

**Issue by baole** [MicrosoftDocs/bot-docs#1960]
When my bot was disabled (or removed/uninstalled) by Teams's admin, my bot received different error codes when posting to a private conversation and channel conversation:

POST https://smba.trafficmanager.net/emea/v3/conversations/[private conversation id]/activities
Response with HTTP 403 Forbiden
```
{
    "error": {
        "code": "TenantNoPermission",
        "message": "Tenant is disabled."
    }
}
```
POST https://smba.trafficmanager.net/emea/v3/conversations/[channel conversation id]/activities
Response with HTTP 502 Bad Gateway

```
{
    "error": {
        "code": "ServiceError",
        "message": "Internal server error"
    }
}
```

Is that an expected behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by mmiele** [comment]
@baole 

- The error **403** means that the bot is not allowed to perform the requested operation. Being the bot disabled/removed this is what to expect in the private scenario, as matter of  a fact the error you get says: "tenant is disabled". 
- The error **502** means that one server received an invalid response from another server. You are trying to connect to the bot via a channel. Because the bot is not "reachable"  you get a server to server communication error. This error is what to expect in this scenario.

See also [HTTP status codes](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#http-status-codes).

**Comment by baole** [comment]
@mmiele  error 502 is not documented.

I understood your explaination. However, the error code and error message doesn't make sense in this case in the bot perspective. i.e "Internal server error" is something that the bot should retry, but in this case, it shouldn't because the bot was removed from the channel. More specific error code/error message could be helpful.

**Comment by mmiele** [comment]
@baole It seems that the problem you are having is with error 502, while your are OK with 403 correct? You are asking for a better explanation of error 502. Do I understand correctly? Thanks

**Comment by baole** [comment]
@mmiele  as the title suggests, the error 502 is misleading.

**Comment by mmiele** [comment]
Every channel that connects to a bot has its own way to handle errors. The table in [HTTP status codes](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#http-status-codes) gives an overview of the main errors.  In your case, for specific information about error 502, you may want pose your question in [Microsoft Teams Developer Community channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback?view=msteams-client-js-latest).
