### ISSUE TITLE
Installing Bot Frameworks Fails if Multiple NuGet Sources

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/bot-docs#1973]
[Enter feedback here]

When I enter the below commands the dotnet CLI doesn't use NuGet.org as the package source. I have multiple sources and it tries to use my private company one first which is denied and then stops there, doesn't try Nuget.org or the offline version. I have to disable my company one for these commands to work.

```
dotnet new -i Microsoft.Bot.Framework.CSharp.EchoBot
dotnet new -i Microsoft.Bot.Framework.CSharp.CoreBot
dotnet new -i Microsoft.Bot.Framework.CSharp.EmptyBot
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-create-basic-bot?view=azure-bot-service-4.0&tabs=csharp%2Cvc)
* Content Source: [articles/v4sdk/bot-builder-tutorial-create-basic-bot.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-create-basic-bot.md)
* Service: **bot-service**
* GitHub Login: @mmiele
* Microsoft Alias: **v-mimiel**

**Comment by jwiley84** [comment]
I was able to partially repro this, as using the commands given in the doc silently fail (or rather technically, they success, but do nothing), and using the template's short name in the command as `dotnet new -i emptybot` leads to a 'cannot find package' error.  I'll try to do a bit more digging, and see what's going on here.

**Comment by v-kydela** [comment]
Thank you for the report, @DanJ210 

There doesn't seem to be a problem with our documentation here. The commands work as expected. I don't know why @jwiley84 reported failure but she may have had different expected behavior.

Your problem seems to be caused by your NuGet configuration and not by anything to do with the Bot Framework. It seems you can overcome the problem by disabling the undesired NuGet source or by using the `--nuget-source` option according to [this documentation](https://docs.microsoft.com/dotnet/core/tools/dotnet-new#options). There may be a way to configure a default NuGet source but that's outside the scope of bot docs.

If you need to report a bug or make a feature request regarding the .NET CLI, you can do so in this repo: https://github.com/dotnet/sdk

If you have any more questions about using the .NET CLI, please feel free to ask them on Stack Overflow. I will close this issue as unrelated.
