### ISSUE TITLE
Webex bot is not responding to other users

### ISSUE THREAD

**Issue by Ashwani27Jaiswal** [MicrosoftDocs/bot-docs#2013]
I have successfully integrated webexbot with Azure ChatBot and is responding to me via Webex Teams. Currently i am facing two issues in that:
1. For other users in my organization webexbot is visible in webex teams but its not responding to them.
2. While responding to me its not showing adaptive cards/buttons on dialogue flow.

Please assist me on above two issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e61be5-e537-8678-f907-10f27ea7bf90
* Version Independent ID: e2a9d88e-0819-9de5-d6f8-48bf7b270685
* Content: [Connect a bot to Webex Teams - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-adapter-connect-webex?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-adapter-connect-webex.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-adapter-connect-webex.md)
* Service: **bot-service**
* GitHub Login: @garypretty
* Microsoft Alias: **gapretty**

**Comment by JonathanFingold** [comment]
@Ashwani27Jaiswal - Please use StackOverflow for this sort of question. If you find errors or omissions in the documentation, than please let us know what the problem is.

Questions can be posted at [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework) using the `botframework` tag. Please note that Stack Overflow has guidelines such as requiring a descriptive title, a complete and concise problem statement, and sufficient details to reproduce your issue. Feature requests or overly broad questions are off-topic; new users should visit the [Stack Overflow Help Center](https://stackoverflow.com/help/how-to-ask) for more details.
