### ISSUE TITLE
Unclear instructions in "To test the bot" section

### ISSUE THREAD

**Issue by oclipa** [MicrosoftDocs/bot-docs#2024]
In the final "To test the bot" section, step 3 simply says "Start the Emulator, connect to your bot, and send messages as shown below." however if you follow the instructions as written, nothing happens because it is not possible to generate the first adaptive card manually in the emulator.  In fact, this card is generated by the OnEventActivityAsync() method, which suggests something needs to have happened first in order to trigger that method and produce the adaptive card.

Either there is information missing from these instructions or something is badly worded.  What needs to happen to trigger the OnEventActivityAsync() method?

Please could this content be reviewed to check what is missing (or what is not obvious to someone unfamiliar with the Bot framework).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afce7fb8-6f98-48ae-ac02-0d13f32a5d43
* Version Independent ID: b2cccd25-c541-4286-3feb-1f2653e8cdea
* Content: [Manage a long-running operation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-howto-long-operations-guidance.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-long-operations-guidance.md)
* Service: **bot-service**
* GitHub Login: @EricDahlvang
* Microsoft Alias: **erdahlva**

**Comment by oclipa** [comment]
I managed to get this working, after a fashion, by adding an override of OnMessageActivityAsync(), which then called Dialog.RunAsync(), however I am guessing this was not the solution intended since this is not mentioned in the example code.

In any event, even though I managed to make progress, I still can only get this to work properly if I deploy the bot to Azure; I still cannot get it to run in the emulator (the Queue Storage trigger receives the message, but the emulator cannot receive the response from DirectLine).

Again, it seems that either the document is out of date, or it is missing vital information.

**Comment by EricDahlvang** [comment]
Hi @oclipa 

Direct Line should be able to connect to your local bot using a proxy suck as ngrok, described here: 

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0#create-a-bot-channels-registration

**Comment by JonathanFingold** [comment]
@oclipa , Thanks for the feedback. A couple things we can make more clear in the article:
1. When following the instructions in section [Create the bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0#create-the-bot) to update the **Bots\DialogBot.cs**, the code in step 4 is meant to be added to the existing bot, and only replace the constructor and the `OnTurnAsync` definitions. That's why you ended up needing to add the `OnMessageActivityAsync` method back in.
2. The tunneling URL that ngrok generates for you is transient, so when it expires, you will need to generate a new one and update your channels registration.

Let me know if that helps. I will try to make the article more clear in the next few weeks.

**Comment by JonathanFingold** [comment]
Closing. Please reopen with comments if you need more information on this.
