### ISSUE TITLE
TranscriptLoggerMiddleware

### ISSUE THREAD

**Issue by paulio** [MicrosoftDocs/bot-docs#208]
It's probably worth pointing out that v4 has dedicated middleware for supporting transcripts. So whilst this is a good example, this is probably not what you would use in production.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b752c3-6cc6-58f7-29cf-d9a122bd854e
* Version Independent ID: 2484117e-596e-21d2-aabe-3506b2602ac0
* Content: [Create middleware using Cosmos DB - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-cosmos-middleware?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-cosmos-middleware.md](https://github.com/Microsoft/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-cosmos-middleware.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@paulio , Unfortunately, for a short topic like this that focuses on the storage mechanism, a more compelling scenario would distract from the information we want to present. Fortunately, there are a growing set of [samples for v4 bots](https://github.com/Microsoft/BotBuilder-Samples).

**Comment by paulio** [comment]
Possibly, for me it's more about the Transcript handling than blob storage but yes a link covering the recommended use of the Transcript middleware would be great.

**Comment by JonathanFingold** [comment]
@paulio Since we started this conversation, the original topic was removed an now redirects to [Write directly to storage](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0), which has a section on [Blob transcript storage
](https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0#blob-transcript-storage). This section covers a few uses of the transcript store. Please comment if this doesn't address your issue, and I'll reopen.

**Comment by xtianus79** [comment]
@JonathanFingold there is not good documentation on this and it seems the library isn't the same in C# and Node... Not with this middleware but what can actually use the middleware such as a database that is either memory or cosmosdb for azure specifically in Nodejs.

**Comment by erhopf** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
