### ISSUE TITLE
Deploying a bot to a local web server?

### ISSUE THREAD

**Issue by FlyingThunder** [MicrosoftDocs/bot-docs#2133]
I dont know if its hidden somewhere, but is there no documentation on how to deploy my bot not on Azure but on my local machine, and then use e.g. ngrok to be able to access it from there via Microsoft Teams? The basic bot example seems to only work with the emulator - my end goal is to have a python script running on my machine and then sending messages to the bot user through the teams client. How can i achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c86f2-9c0d-015b-d44f-58914fed2deb
* Version Independent ID: 85fe7f0c-002a-e449-55cb-712d92874b19
* Content: [Create a bot with the Bot Framework SDK in C#, Java, JavaScript, or Python - Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs)
* Content Source: [articles/bot-service-quickstart-create-bot.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-service-quickstart-create-bot.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by dmvtech** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework).  Please open a question there.

**Comment by dmvtech** [comment]
> I don't know if its hidden somewhere, but is there no documentation on how to deploy my bot not on Azure but on my local machine, and then use e.g. ngrok to be able to access it from there via Microsoft Teams?

There is no documentation for doing so, and there likely won't be. It can be hosted on IIS or any other sort of web server. You can host your bot anywhere as long as it is accessible by the connector service (using https, etc). 

> The basic bot example seems to only work with the emulator - my end goal is to have a python script running on my machine and then sending messages to the bot user through the teams client. How can i achieve that?

If configured correctly, you should be able to test any channel with a locally running bot using ngrok. I'm not clear on the implementation of the python script you reference above, but I would ask this; do normal (user) messages sent from Teams get to the bot running locally through ngrok?

**Comment by FlyingThunder** [comment]
I wrote it a bit missleading with "local machine" - as you said it can be hosted on an IIS or webserver, but i couldnt find any documentation on it - [the docs](https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0) have a quickstart for "Creating a basic bot" (which is offline online and can only be interacted through via the Emulator, not the Teams Client as far as i can tell?), and then jumps straight to "Create an Azure Bot Resource" - where is e.g. "Host a bot on Microsoft IIS" documentation? Do you get what i mean - what if i want to make a proper, productive bot, but without using Azure? 
This is something Microsoft specific that i have to know - in the example of Webex, i know i have to:
1) host my bot script and provide it with the bots access token
2) open an ngrok tunnel on the host
3) create a webhook that points to the ngrok tunnel.
And thats it, my bot is usable.
But in the case of Microsoft Teams? I have no idea what it needs.

**Comment by dmvtech** [comment]
> I wrote it a bit missleading with "local machine" - as you said it can be hosted on an IIS or webserver, but i couldnt find any documentation on it - [the docs](https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0) have a quickstart for "Creating a basic bot" (which is offline online and can only be interacted through via the Emulator, not the Teams Client as far as i can tell?), 

[This](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) is the documentation on using Ngrok from any channel. You can use any channel to test with your locally running bot, including **Teams**.

>  where is e.g. "Host a bot on Microsoft IIS" documentation? Do you get what i mean - what if i want to make a proper, productive bot, but without using Azure?

This documentation does not exist. It is _not_ a common scenario, and not involved enough to warrant documentation. i.e. if you can test a bot running locally with IIS Express and Ngrok, then it should work with IIS. Most of your work is going to be around making sure the bot/application is accessible from the internet and connector service (firewall, etc).

The bot registration still needs to live in Azure, but your endpoint can live anywhere (IIS, Apache, etc), as long as it's accessible. If you don't want to use an Azure bot registration (Azure Bot | Web App Bot | Bot Channels Registration), then you can use things like [channel adapters](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-additional-channels?view=azure-bot-service-4.0) (which don't use channel connectors. You _**will not**_ be able to do this with Teams. Webex is an example of a channel _adapter_). Depending on your needs [Offline Directline](https://www.npmjs.com/package/offline-directline) might be of use as well. 

> This is something Microsoft specific that i have to know - in the example of Webex, i know i have to:
> 
> 1. host my bot script and provide it with the bots access token
> 2. open an ngrok tunnel on the host
> 3. create a webhook that points to the ngrok tunnel.
>    And thats it, my bot is usable.
>    But in the case of Microsoft Teams? I have no idea what it needs.

For Teams; you need to have:

1. A bot registration with the [Teams channel enabled](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0).
2. Ngrok if testing Teams on a local running bot. Otherwise; an endpoint that can be reached publicly, configured in the bot registration's `Messaging endpoint`.
3. If you _**want**_ to use specific features of Teams, please look to the functionality/APIs shown in the [Teams specific samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore).
