### ISSUE TITLE
`az ad app create` command doesn't work. "password" argument is not recognized

### ISSUE THREAD

**Issue by piotrek-k** [MicrosoftDocs/bot-docs#2206]
Registering new app using this command no longer work ("Create an identity resource" section, "Multi-tenant" tab) 
```
az ad app create --display-name "<name>" --password "<password>" --available-to-other-tenants
```

Output after trying to run this command:
```
This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
unrecognized arguments: --password [password here] --available-to-other-tenants
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Publish your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=userassigned%2Cnewgroup%2Ccsharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs-pr/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **iawilt**

**Comment by anishprasad01** [comment]
Hi @piotrek-k,

As mentioned in the [documentation](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration) linked in the error message, Azure CLI version `2.37.0` introduces breaking changes in the functionality of various commands due to the required migration to Microsoft Graph from the deprecated AAD Graph.

At the moment, older versions of Azure CLI should support those older commands, and we are working on getting documentation updated. Essentially, this is expected behavior, and the document should help explain which commands to use instead.

**Comment by JonathanFingold** [comment]
Instructions will indicate that (for now) Azure CLI v2.36 should be used for C#, JavaScript, and Python bots.

**Comment by jpiabrantes** [comment]
It should also tell people how to downgrade or install the correct out-dated version
