### ISSUE TITLE
Cannot Access Some Documentation

### ISSUE THREAD

**Issue by happyparm** [MicrosoftDocs/bot-docs#2207]
Hi, earlier today I tried to access the migration documentation: https://docs.microsoft.com/en-us/azure/bot-service/migration/migration-overview

and I now get an error 404 when opening the link, while it worked just fine yesterday

**Comment by JonathanFingold** [comment]
I retired the migration articles yesterday, but old links should be redirecting to live articles, instead of generating 404s.

Unfortunately, the conversion guidance had fallen behind current recommended usage. Let me know if there's a specific question you have.

I'll research and try to fix the redirection/404 issue.

**Comment by JonathanFingold** [comment]
Found my error. By end of day, the links should start redirecting to the intro concept for the v4 SDK [Basics of the Bot Framework Service](https://docs.microsoft.com/azure/bot-service/bot-builder-basics).

**Comment by JonathanFingold** [comment]
Verified that the page redirect correctly now.
