### ISSUE TITLE
To create an Azure AD v2 application

### ISSUE THREAD

**Issue by hvklaveren** [MicrosoftDocs/bot-docs#242]
Under Application Secrets, click Generate New Password  : this is already been done when creating the bot in azure. or do we need to create another New Password

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60d80e0b-f1b7-175b-128d-0fb12f17ae36
* Version Independent ID: 1ed9006a-bf0b-9aaa-d180-9d2cb0c09524
* Content: [Add authentication to your bot via Azure Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0#to-create-an-azure-ad-v2-application)
* Content Source: [articles/bot-builder-tutorial-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-tutorial-authentication.md)
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **JonathanFingold**

**Comment by EricDahlvang** [comment]
The generated password can be retrieved from the resource group Deployments, as described here: https://blog.botframework.com/2018/07/03/find-your-azure-bots-appid-and-appsecret/

**Comment by Kaiqb** [comment]
Thank you for taking the time to share your product and documentation feedback with us. Your input is valued because it helps us create the right documentation for our customers. 
Due to the volume of issues in our queue, our policy is to close issues that have been inactive for the last 90 days. We hope to continue hearing from you. 
Thank you.
