### ISSUE TITLE
Request URL for bot API

### ISSUE THREAD

**Issue by Richienb** [MicrosoftDocs/bot-docs#335]
What JSON URL do I have to query using Jquery's `$.getJSON` function to get a chat response?

**Comment by JonathanFingold** [comment]
@Richienb , Is this question with respect to the Bot Framework Web Chat?

If so, you can find more information on that project's repo: https://github.com/microsoft/botframework-webchat. Otherwise, if you have a question about the Bot Framework SDK, you can get help from our support team. https://stackoverflow.com/questions/tagged/botframework.
