### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/bot-docs#400]
Nuget packages seem outdated. There's no "Microsoft.Bot.Builder.Ai" but instead there's for instance "Microsoft.Bot.Builder.Ai.Lois". When you guys churn, please be sure to keep the docs in sync! Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c406c6-b851-189e-4996-4e9ec7b6079b
* Version Independent ID: 4d5e7967-bddf-818d-1a6b-1a1ca4628bf4
* Content: [Translate user input to make your bot multilingual - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-how-to-translation?view=azure-bot-service-4.0&tabs=csrefs%2Ccssetuptranslate%2Ccshelp%2Ccstranslateback%2Ccschangelanguage%2Ccslanguageluis%2Ccsbypass%2Ccstranslation)
* Content Source: [articles/v4sdk/bot-builder-how-to-translation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-how-to-translation.md)
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by stofte** [comment]
In general, code references classes that do not exists, does not specify nuget versions (just "prerelease").

**Comment by ivorb** [comment]
This page is no longer linked to and updated by our docs, so these don't get updated. For current usage of translation, take a look at our sample (JS has the same one if you prefer) https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot

Where did you see the misspelled "Lois"? The docs should be updated with the current usage of the libraries, but if we missed one that's definitely something we want to fix!

**Comment by stofte** [comment]
Is there any way to see that this is "outdated"/no longer maintained? At the top of the page it states this page is for the latest SDK. 

The nuget naming issue is not about mispelling, but about referencing packages that do not exist (eg. "Microsoft.Bot.Builder.Ai" which does not exists). The code itself also uses classses that cannot be found in the indicated nuget packages.

Thanks for the link to the other sample. Unfortunantly, I found that repo the other day as well, but I frankly find the sample somewhat useless as it's unclear what is "bot framework" best practise, and what is the minimal code example (its a sample I could spend days taking apart, when I expected translation to be a something I could wise up in a few hours). Other Translation Text apis samples would reduce the minmal code to just the HTTP post, which I found way too reduced.

**Comment by ivorb** [comment]
It is not longer updated if it isn't included in the Table of Contents on the left - usually you'll see the page you're currently on highlighted in blue. If there is nothing highlighted it's not in the TOC and likely outdated. The only way you would be reaching a page like that is if you have the link saved/bookmarked - all links to it from our docs are removed when we no longer update the page.

Do you mean as opposed to "Microsoft.Bot.Builder. **AI**"? All of the up to date articles should reflect that new package naming, including the sample code in our articles.

The actual translation is still done with the TranslationMiddleware, which is added in Startup.cs > ConfigureServices, which is similar to how it is in the article this issue was originally logged against. If you look at Startup.cs, line 125-128, you'll see the initialization of it has changed, but it works similarly in the end. That initialization code, the provided translation middleware, and the short bit in MultiLingualBot.cs > OnTurnAsync should be all you need - if it's not clear enough there, I'm happy to try to help

**Comment by Kaiqb** [comment]
@stofte - We will also add a redirect to the sample.

**Comment by kichinsky** [comment]
Hi, it seems like the redirect is still not implemented.
