### ISSUE TITLE
endOfConversation does not close conversation

### ISSUE THREAD

**Issue by ukphillips** [MicrosoftDocs/bot-docs#407]
After sending the endOfConversation event to direct line, subsequent activities can still be posted to direct line in the conversation, the activities are accepted and stored so they show up when reading all activities in the conversation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174f2cb3-cad3-7d6b-3682-6fae14b1f632
* Version Independent ID: 2f9132db-9d77-0a7a-d6d1-ba140354b388
* Content: [End a conversation - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-end-conversation?view=azure-bot-service-4.0#additional-resources)
* Content Source: [articles/rest-api/bot-framework-rest-direct-line-3-0-end-conversation.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-direct-line-3-0-end-conversation.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment]
@ukphillips How to react to an endOfConversation activity is up to each channel. If you are designing a DirectLine client, they you would update the client to behave appropriately, such as generating an error if the bot sent an activity to a conversation that has already ended.

**Comment by ukphillips** [comment]
This documentation at best is extremely misleading. It indicates that once the endOfConversation activity is sent, subsequent messages are not accepted (in the context of direct line). Are you saying this needs to be handled explicitly in the bot and/or on the client? How would you identify if a conversation is ended from the client side (is this just additional internal state tracking within the bot?). That's fine the documentation just does not lead one to believe this.

**Comment by JonathanFingold** [comment]
The article is misleading, or simply too vague. I'm reopening this so that it gets into our backlog.

From the bot-side, when the bot receives an incoming message, it replies on the same conversation. If the channel ended the conversation, then one would expect the channel not to send further activities on that conversation, but initiate a new one. If the bot receives an endOfConversation activity, it should be able to purge conversation state, and not have to worry about it past that.

From the DirectLine client-side, how it handles an endOfConversation activity from the bot is up to the developer of the client. The dev should be explicit whether their client reacts to this activity, and if so, how.

Does that explanation help?

**Comment by Kaiqb** [comment]
@ukphillips @JonathanFingold - pushing a fix to the live site now based on the comments in this issue.
