### ISSUE TITLE
Definition of objects is inconsistent....

### ISSUE THREAD

**Issue by cmayomsft** [MicrosoftDocs/bot-docs#471]
Why are the prompt/userName/telephoneNumber field defined with literals in some places and strings in others?

    // read from state and set default object if object does not exist in storage.
    let topicState = await this.topicState.get(turnContext, {
        //Define the topic state object
        prompt: "askName"
    });
    let userProfile = await this.userProfile.get(turnContext, {  
        // Define the user's profile object
        "userName": "",
        "telephoneNumber": ""
    });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Manage conversation and user state - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&branch=live&tabs=js)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment]
@cmayomsft Since we pull from the samples repo, we don't generally change their code, and sometimes the samples themselves vary a bit. This should settle out to a consistent code style across samples, but I'm not sure how soon.

For larger blocks of sample code, I tend to define constants for IDs. For smaller snippets, I may use string literals to keep the focus on what I'm trying to highlight in that section. There's a trade-off either way. Do you have a useful rubric that you use?

**Comment by Kaiqb** [comment]
I've raised this as an issue with the team.

**Comment by JonathanFingold** [comment]
@cmayomsft Closing this for now. We should be moving toward a more consistent style over time.
