### ISSUE TITLE
BOT user message says "couldnt send retry"

### ISSUE THREAD

**Issue by MarellaRam** [MicrosoftDocs/bot-docs#566]
it works fine but when I made it to wait the job processing for few seconds then I see all working fine except the input "Run" always says in "Couldnt Send retry" but indeed message was sent and responded back to BOT as well after the wait time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc28a40-716e-22bc-8944-15f0a8b0d5c2
* Version Independent ID: 86252b0d-94e2-2ea6-ed17-fc32ae38e6fc
* Content: [Get notification from bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-proactive-message.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-proactive-message.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **jonathanfingold**

**Comment by JonathanFingold** [comment]
Two comments:
1. In general, the turn context object is disposed when the bot's on turn handler exits, so if you did not wait for the delayed message to be sent, you might get a null reference exception at run time.
2. However, adding a delay misses the point of the example. The bot saves the conversation reference associated with each "job" so that it can send the "completed" message back to that conversation, regardless of the conversation used to notify the bot that the job completed.

Hope that helps clarify.
