### ISSUE TITLE
Too unstable... bugs

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/bot-docs#651]
I literally just followed all the steps in [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0) tutorial, choosing a JS echo bot. I then used the web chat testing feature and experienced failed messages:
![image](https://user-images.githubusercontent.com/791996/50112375-f1fbc300-01f3-11e9-9a05-5fa6bc947649.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by DanDev33** [comment]
Thanks for your feedback Yousef. There are reported issues with the Web Chat tool in Azure. In the meantime here are a few things you can try to improve performance issues:

1. after selecting your Web App Bot, click on channels and the Web Chat edit button.
![edit web chat](https://user-images.githubusercontent.com/40217323/50249597-52753680-0393-11e9-875d-99390ee892f3.png)
2. When the Edit page opens, scroll down to the bottom, uncheck the Enable Preview option, and select Done. (This improves the tool's performance)
3. If you are experiencing issues due to msg delivery delay, you can also try the following: Select the App Service plan and  Scale it up from Free (F1) to Small (S1), Run your test, then scale it back down to Free when you are finished.

Hope these short term workarounds help with your Web Chat performance issue.

**Comment by DanDev33** [comment]
Closing this feedback PR.
