### ISSUE TITLE
Continuous deployment docs should be recommended and link to creation of a bot through ABS.

### ISSUE THREAD

**Issue by lucashuet93** [MicrosoftDocs/bot-docs#653]
CD through GitHub/Azure Dev Ops is the easiest means of deployment and is best practice and the docs should reflect that. At the moment, they are presented as the last step  in the deployment story once the developer has deployed via CLI, VS, etc. Instead, the CD docs should be re-titled to something like 'Deploy via source control", have links to initial ABS creation before deployment via source control, and be the top option in the documentation under deploy.

**Comment by Kaiqb** [comment]
There is a note at the top of the article that tells the user that they need to have a bot already deployed to the Azure portal before following steps in this article. The reason is that your bot needs to be deployed into an existing bot in Azure first and there are manual steps that users must do to set things up correctly. Once that is done, you can set up CD. Hope this clarifies it.
