### ISSUE TITLE
Manually create QnA Maker app error

### ISSUE THREAD

**Issue by DONGZHUPENG** [MicrosoftDocs/bot-docs#661]
When import the "" file and create KB, it raised error:
Bad Argument
Failed to extract QnAs from the source QnAMaker.tsv - Unsupported / Invalid url(s). Failed to extract Q&A from the source

Did anyone try it successfully? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f68e3448-ea66-7aab-26d2-37de5f44527c
* Version Independent ID: 30c9096c-926c-3b92-6ab0-cc49edf63842
* Content: [Use multiple LUIS and QnA models - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-dispatch.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-dispatch.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment]
Thanks again for your feedback. I suspect that this is caused by the same issue I talked about in issue #660. The .json and .tsv files are located in the following GitHub repository: https://github.com/Microsoft/BotFramework-Samples 
Cloning or downloading this repository provides you with local access to these files.

**Comment by DanDev33** [comment]
closed - article updated.
