### ISSUE TITLE
Error deploying the Azure search component when bot's name has an underscore in it ( _ )

### ISSUE THREAD

**Issue by jjgriff93** [MicrosoftDocs/bot-docs#703]
There is a naming convention error with the deployment template when deployign Azure Search. Because our bots name had an underscore it got to this stage and failed. There should be a warning in the documentation or a catch for this in the script:

Command failed: az search service create -g PoC_TonyBot -n "poc_tonybot-search" --location northeurope --sku standard --subscription XXXXXXXXXXXXXXXXXXXXXXXX ERROR: Service name 'poc_tonybot-search' is invalid: Service name must only contain lowercase letters, digits or dashes, cannot start or end with or contain consecutive dashes and is limited to 60 characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615eae0a-7bae-820c-8fda-09fb0899bd0f
* Version Independent ID: c2e5b308-760c-1226-ba9b-bef7ae535fca
* Content: [Enterprise Bot Template Deployment - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-enterprise-template-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-enterprise-template-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @darrenj
* Microsoft Alias: **darrenj**

**Comment by DanDev33** [comment]
Thanks for your feedback James! As you found out, because YOUR_BOT_NAME is defining an Azure Service Name it has tighter character restrictions. I'm updating this article prior to our showing the msbot call to warn users of this restriction. I'll also change the name YOUR_BOT_NAME to YOUR-BOT-NAME since underscores are restricted for this by Azure. 

You should see these changes go live fairly soon. Thanks for helping us make our docs better!
