### ISSUE TITLE
Welcome message pattern doesn't work fine in web chat

### ISSUE THREAD

**Issue by sbaidachni** [MicrosoftDocs/bot-docs#779]
Suggested action example demonstrates how to display buttons right after welcome message. If you run this example in web chat (on the Azure portal, for example), ConversationUpdate will fire after any message from user only. So, if user type "Hi" or something like this, the example displays welcome message and buttons and, obvious, hi should be ignored, but it's not happening and "Hi" is moving to "ProcessInput". It looks like a problem about Welcome pattern in general (no way to say Welcome and ask display navigation using ConversationUpdate in WebChat), but this example demonstrates it very well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53446ad1-6b8c-1ccb-6e78-2cb14358b1c3
* Version Independent ID: 8b0fcc34-e624-64a9-adc8-6c8fa3031f54
* Content: [Use button for input - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-suggested-actions?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-howto-add-suggested-actions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-add-suggested-actions.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by Kaiqb** [comment]
The issue here is that different channels behave differently, so have one example wouldn't necessarily work for all. We are having discussion within the team about providing some help in this area, and when it is ready, we will update the docs + SDK.

**Comment by mutanttech** [comment]
Hi @Kaiqb,
 This issue was closed in early Feb and it's now July. I am hoping that Microsoft team should have decided on how to approach this for different channels. The whole community is baffled by this one issue, with no clear indication on how to solve it and thanks to ever-changing templates, it never helps.
Anyways while this was so easier with v3, I wanted to know if your team has found any way to correctly solve this problem. I have been trying to use older Web Chat and new V4 SDK C# + dot net core.
Please help here.
Thanks.
