### ISSUE TITLE
ste by step

### ISSUE THREAD

**Issue by hvklaveren** [MicrosoftDocs/bot-docs#812]
where is the old step by step documentation  gone. this was very usefull

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa9e2e6-b901-9e27-d070-701922396a4c
* Version Independent ID: c29a68b2-886d-2cec-0ce7-c49c586d7ea8
* Content: [Create a bot with Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-4.0#next-steps-1)
* Content Source: [articles/bot-service-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-quickstart.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **v-ducvo**

**Comment by ivorb** [comment]
If you're looking for the old documentation, [try here for v3 docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart?view=azure-bot-service-3.0). Otherwise, we feel our V4 documentation builds up in complexity. Is there something you're not seeing that you would like to see? If you're struggling to follow an article, I'd love to know which ones and what we can do to improve it.

**Comment by Kaiqb** [comment]
The old docs that covered creating SDK v3 .NET or Node.js bots was removed after SDK v4 was released. The only quickstart we have for SDK v3 is using the Azure portal.
