### ISSUE TITLE
Specify setting the .bot file property to "Copy Always"

### ISSUE THREAD

**Issue by BruceHaley** [MicrosoftDocs/bot-docs#918]
In the "Update your local .bot file" section, it might help to add the following sentence: 
"In Solution Explorer, ensure that the .bot file's property "Copy to Output Directory" is set to "Copy always"." The sample bot I tried, https://github.com/Microsoft/BotFramework-Samples/tree/master/SDKV4-Samples/dotnet_core/StateBot , had the setting "Do not copy". (Might be nice to get that sample fixed also.) "Do not copy" meant the .bot file was not included in the deployment to Azure. Azure "Test in Web Chat" then hung with the message "Waiting for bot to be ready". No error displayed. As a newbie, this took me days to solve. Thanks for listening. --Bruce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Hi @BruceHaley thanks for reporting! I opened an issue for samples to fix that - https://github.com/Microsoft/BotBuilder-Samples/issues/1284 - since it would be very confusing to figure out. We adjusted our guidance to be as you read to try to avoid that issue (previously, we had said to copy over the entire .bot file and change your bot to use that, but we faced the same issue you're hitting while doing so). I'll also add a tip to the article.
