### ISSUE TITLE
SetAsync() method was never called in this tutorial?

### ISSUE THREAD

**Issue by benamarm** [MicrosoftDocs/bot-docs#939]
Hi, could you please explain how the user profile data still gets saved by the state, despite never calling the SetAsync method? In all previous tutorials we called SetAsync() followed by SaveChanges(). But this tutorial only calls SaveChanges(). I tried reproducing this behavior in another tutorial by commenting out the SetAsync() call and leaving only the SaveChanges() call, but it didn't save the data... I'm puzzled, why does this tutorial not need SetAsync() while the other does? The other tutorial I'm talking about is this one: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c5adf9-272a-e0f1-10f1-c8365e76035b
* Version Independent ID: 1982af41-5a06-4398-0e95-abcc50864e0d
* Content: [Implement sequential conversation flow - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-dialog-manage-conversation-flow.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by JonathanFingold** [comment]
In this sample, the user profiles' get and set async methods are being called from within the dialog steps, but the user state's save changes async method is called in the turn handler, after the dialog is continued.

**Comment by benamarm** [comment]
I am sorry but the dialog steps do not call the SetAsync() method. They only call the GetAsync() method. Maybe the source code is out of date? But this still doesn't give an answer. The project runs fine and saves the data even though it nevers calls SetAsync()...

**Comment by JonathanFingold** [comment]
No worries, I read through this too quickly. Here's why this works without calling SetAsync. (I'll refer to some information that's in the [state property accessor methods](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state#how-the-state-property-accessor-methods-work) section of the **Managing state** topic.)
1. The first GetAsync call in a turn creates and populates an entry in the state cache. It then returns a reference to that "cached object".
   - As long as the dialog code keeps this reference intact, any changes to that reference are being made to the cache. (This isn't considered "best practice", but that's what's in this sample at the moment.)
   - If you had a state property accessor for a C# value type, the reference would immediately be lost, due to the way C# handles value types. The user profile property is a reference type, so we're okay.
   - If the dialog had created a new object, and wanted to assign that as the value of the property, then the dialog would need to call SetAsync to update the cache.
1. When the turn handler calls SaveChangesAsync, the cache is written back out to storage.

The samples in the repo are scheduled to be updated in a couple weeks, and we're working on updated how-to topics to go with them. Until then, I hope this explanation helps.

**Comment by JonathanFingold** [comment]
@benamarm Closing. Please reopen if you are still blocked.
