### ISSUE TITLE
bool PromptedUserForName

### ISSUE THREAD

**Issue by jasonMunsterteiger** [MicrosoftDocs/bot-docs#975]
I enjoyed the Tutorial and it helped me understand, but I do not understand the need to set the bool, PromptedUserForName, to false in the OnTurnAsync.  
I am referring to the code in the 'true' condition of the 'if (conversationData.PromptedUserForName)' statement.

Thanks,
Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment]
Hi Jason,
Thanks for your feedback! Since this code runs a sample, when the logic is finished setting the bool value back to "true" resets the code to run through the demo logic again. It is preceded by a comment:
// Reset the flag to allow the bot to go though the cycle again.
In a production bot, you would not reset this flag once the data you need had been acquired and saved.
