### ISSUE TITLE
why delete the botFileSecret in the last step?

### ISSUE THREAD

**Issue by NoPinky** [MicrosoftDocs/bot-docs#990]
Why do you delete the botFileSecret in the last step? Is it because you uploaded an unencrypted *.bot file in the steps before? Does it create some security issues if you deploy an unencrypted .bot file?
Just telling to delete it without explaining is bad style in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial to create and deploy a basic bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by ivorb** [comment]
Yes, this is due to not having the file encrypted, so try to decrypt it again in Azure after you deploy would cause your bot to fail. If you are deploying a bot for production, you should encrypt your secrets but for the sake of this tutorial, aimed at simple deploying of a bot, that is unnecessary.

We do explain why you delete it, or how to reencrypt it, in other articles, and changes to deployment will be coming soon to all topics.
